-- Fergus (fergusmc@ie.ibm.com)
ECHO ************************************;
ECHO CAPTURING DUBPERF_DB DIFF DATA;
ECHO ************************************;
INSERT INTO dbmon.dubperf_DB_diff
(
	START_TIMESTAMP,
        END_TIMESTAMP,

	DURATION_DAYS,
	DURATION_HOURS,
	DURATION_MINS,
	DURATION_SECS,
	DURATION_USECS,


        DB_NAME,
        DB_PATH,
        INPUT_DB_ALIAS,
        DBPARTITIONNUM,
        DB_STATUS,


	-- new 02May13
	CATALOG_PARTITION,
	CATALOG_PARTITION_NAME,
	SERVER_PLATFORM,
	DB_LOCATION,
	-- 17May13 update
	START_CONNECTIONS_TOP,
	END_CONNECTIONS_TOP,
	START_APPLS_CUR_CONS,  	-- Appls currently connected to DB
	END_APPLS_CUR_CONS,  	-- Appls currently connected to DB
	START_APPLS_IN_DB,  	-- Appls currently executing in DB
	END_APPLS_IN_DB,  	-- Appls currently executing in DB

	TOTAL_CONS,
	TOTAL_SEC_CONS,

	START_NUM_ASSOC_AGENTS,	-- Current number of subagents
	END_NUM_ASSOC_AGENTS,	-- Current number of subagents
	START_AGENTS_TOP,	-- Top number agents in DB
	END_AGENTS_TOP,		-- Top number agents in DB
	START_COORD_AGENTS_TOP,		-- Top number SUBagents in DB
	END_COORD_AGENTS_TOP,		-- Top number SUBagents in DB


	PKG_CACHE_NUM_OVERFLOWS,

        --Lock Info

        LOCKS_HELD, --CURRENT, NOT CUMULATIVE
        LOCK_WAITS,
        LOCK_WAIT_TIME,
        LOCK_TIMEOUTS,
        DEADLOCKS,

        --Statement Types

        COMMIT_SQL_STMTS,
        ROLLBACK_SQL_STMTS,
        SELECT_SQL_STMTS,
        UID_SQL_STMTS,
        DDL_SQL_STMTS,
        FAILED_SQL_STMTS,
        DYNAMIC_SQL_STMTS,
        STATIC_SQL_STMTS,
	INT_AUTO_REBINDS,
	INT_COMMITS,
	INT_DEADLOCK_ROLLBACKS,
	INT_ROLLBACKS,
	INT_ROWS_DELETED,
	INT_ROWS_INSERTED,
	INT_ROWS_UPDATED,

        --Buffer Pool

        POOL_ASYNC_DATA_READS,
        POOL_ASYNC_DATA_WRITES,
        POOL_ASYNC_INDEX_READS,
        POOL_ASYNC_INDEX_WRITES,

        POOL_DATA_L_READS,
        POOL_DATA_P_READS,
        POOL_DATA_WRITES,

        POOL_TEMP_DATA_L_READS,
        POOL_TEMP_DATA_P_READS,
        POOL_TEMP_INDEX_L_READS,
        POOL_TEMP_INDEX_P_READS,

        POOL_INDEX_L_READS,
        POOL_INDEX_P_READS,
        POOL_INDEX_WRITES,
        POOL_READ_TIME,
        POOL_WRITE_TIME,

        POOL_NO_VICTIM_BUFFER,
        POOL_DRTY_PG_STEAL_CLNS,

        --Direct IO
        DIRECT_READS,
        DIRECT_WRITES,
        DIRECT_READ_REQS,
        DIRECT_WRITE_REQS,

        --Sorting

        TOTAL_SORTS,
        SORT_OVERFLOWS,
        TOTAL_SORT_TIME,

        --Row Access

        ROWS_READ,
        ROWS_SELECTED,
        PREFETCH_WAIT_TIME,

	ROWS_DELETED,
	ROWS_INSERTED,
	ROWS_UPDATED,
	BINDS_PRECOMPILES,
	APPL_SECTION_LOOKUPS,
	APPL_SECTION_INSERTS,
	CAT_CACHE_LOOKUPS,
	CAT_CACHE_INSERTS,
	CAT_CACHE_OVERFLOWS,
	TOTAL_HASH_JOINS,
	TOTAL_HASH_LOOPS,
	HASH_JOIN_OVERFLOWS,
	HASH_JOIN_SMALL_OVERFLOWS,
	TOTAL_OLAP_FUNCS,
	OLAP_FUNC_OVERFLOWS,


        --PACKAGE ACCESS

        PKG_CACHE_LOOKUPS,
        PKG_CACHE_INSERTS,

        --Log Writing Activity

        LOG_WRITES,
        LOG_WRITE_TIME_S,
        LOG_WRITE_TIME_NS,
        NUM_LOG_WRITE_IO,
        NUM_LOG_READ_IO,
        NUM_LOG_PART_PAGE_IO,
        NUM_LOG_BUFFER_FULL,
        LOG_HELD_BY_DIRTY_PAGES,

	--17May13, other related log info
	LOG_READS,	--Number of log pages read from disk by logger.
	LOG_READ_TIME_S,	-- time spent reading log data from disk.
	LOG_READ_TIME_NS,
	NUM_LOG_DATA_FOUND_IN_BUFFER,--nbr of reads by agents from log buffer (not disk).
	APPL_ID_OLDEST_XACT,	--app/agentid of oldest trn.
	LOG_TO_REDO_FOR_RECOVERY, --number of LOG bytes to REDO for crash recovery.
	
	STATS_CACHE_SIZE,
	STATS_FABRICATIONS,
	SYNC_RUNSTATS,
	ASYNC_RUNSTATS,
	STATS_FABRICATE_TIME,  	--msecs
	SYNC_RUNSTATS_TIME,	--msecs
	NUM_THRESHOLD_VIOLATIONS
)
SELECT
        s.SNAPSHOT_TIMESTAMP,
        e.SNAPSHOT_TIMESTAMP,

	DAY    (e.SNAPSHOT_TIMESTAMP - s.SNAPSHOT_TIMESTAMP),
	HOUR   (e.SNAPSHOT_TIMESTAMP - s.SNAPSHOT_TIMESTAMP),
	MINUTE (e.SNAPSHOT_TIMESTAMP - s.SNAPSHOT_TIMESTAMP),
	SECOND (e.SNAPSHOT_TIMESTAMP - s.SNAPSHOT_TIMESTAMP),
	MICROSECOND (e.SNAPSHOT_TIMESTAMP - s.SNAPSHOT_TIMESTAMP),

        e.DB_NAME,
        e.DB_PATH,
        e.INPUT_DB_ALIAS,
        e.DBPARTITIONNUM,
        e.DB_STATUS,

	-- new 02May13
	e.CATALOG_PARTITION,
	e.CATALOG_PARTITION_NAME,
	e.SERVER_PLATFORM,
	e.DB_LOCATION,

-- UPDATED 17May13
	s.CONNECTIONS_TOP,
	e.CONNECTIONS_TOP,
	s.APPLS_CUR_CONS,  	-- Appls currently connected to DB
	e.APPLS_CUR_CONS,  	-- Appls currently connected to DB
	s.APPLS_IN_DB2,  	-- Appls currently executing in DB
	e.APPLS_IN_DB2,  	-- Appls currently executing in DB

	e.TOTAL_CONS		- s.TOTAL_CONS,
	e.TOTAL_SEC_CONS	- s.TOTAL_SEC_CONS,

	s.NUM_ASSOC_AGENTS,	-- Current number of subagents
	e.NUM_ASSOC_AGENTS,	-- Current number of subagents
	s.AGENTS_TOP,		-- Top number agents in DB
	e.AGENTS_TOP,		-- Top number agents in DB
	s.COORD_AGENTS_TOP,	-- Top number agents in DB
	e.COORD_AGENTS_TOP,	-- Top number agents in DB
	

	e.PKG_CACHE_NUM_OVERFLOWS - s.PKG_CACHE_NUM_OVERFLOWS,

        --Lock Info

        e.LOCKS_HELD, 		--CURRENT, NOT CUMULATIVE
        e.LOCK_WAITS            - s.LOCK_WAITS,
        e.LOCK_WAIT_TIME        - s.LOCK_WAIT_TIME,
        e.LOCK_TIMEOUTS         - s.LOCK_TIMEOUTS,
        e.DEADLOCKS             - s.DEADLOCKS,

        --Statement Types

        e.COMMIT_SQL_STMTS  	- s.COMMIT_SQL_STMTS,
        e.ROLLBACK_SQL_STMTS    - s.ROLLBACK_SQL_STMTS,
        e.SELECT_SQL_STMTS      - s.SELECT_SQL_STMTS,
        e.UID_SQL_STMTS         - s.UID_SQL_STMTS,
        e.DDL_SQL_STMTS     	- s.DDL_SQL_STMTS,
        e.FAILED_SQL_STMTS 	- s.FAILED_SQL_STMTS,
        e.DYNAMIC_SQL_STMTS	- s.DYNAMIC_SQL_STMTS,
        e.STATIC_SQL_STMTS      - s.STATIC_SQL_STMTS,
	e.INT_AUTO_REBINDS	- s.INT_AUTO_REBINDS,
	e.INT_COMMITS		- s.INT_COMMITS,
	e.INT_DEADLOCK_ROLLBACKS	- s.INT_DEADLOCK_ROLLBACKS,
	e.INT_ROLLBACKS		- s.INT_ROLLBACKS,
	e.INT_ROWS_DELETED	- s.INT_ROWS_DELETED,
	e.INT_ROWS_INSERTED	- s.INT_ROWS_INSERTED,
	e.INT_ROWS_UPDATED	- s.INT_ROWS_UPDATED,

        --Buffer Pool

        e.POOL_ASYNC_DATA_READS         - s.POOL_ASYNC_DATA_READS,
        e.POOL_ASYNC_DATA_WRITES        - s.POOL_ASYNC_DATA_WRITES,
        e.POOL_ASYNC_INDEX_READS        - s.POOL_ASYNC_INDEX_READS,
        e.POOL_ASYNC_INDEX_WRITES       - s.POOL_ASYNC_INDEX_WRITES,

        e.POOL_DATA_L_READS     	- s.POOL_DATA_L_READS,
        e.POOL_DATA_P_READS     	- s.POOL_DATA_P_READS,
        e.POOL_DATA_WRITES		- s.POOL_DATA_WRITES,

        e.POOL_TEMP_DATA_L_READS        - s.POOL_TEMP_DATA_L_READS,
        e.POOL_TEMP_DATA_P_READS        - s.POOL_TEMP_DATA_P_READS,
        e.POOL_TEMP_INDEX_L_READS       - s.POOL_TEMP_INDEX_L_READS,
        e.POOL_TEMP_INDEX_P_READS       - s.POOL_TEMP_INDEX_P_READS,

        e.POOL_INDEX_L_READS    - s.POOL_INDEX_L_READS,
        e.POOL_INDEX_P_READS    - s.POOL_INDEX_P_READS,
        e.POOL_INDEX_WRITES     - s.POOL_INDEX_WRITES,
        e.POOL_READ_TIME        - s.POOL_READ_TIME,
        e.POOL_WRITE_TIME       - s.POOL_WRITE_TIME,

        e.POOL_NO_VICTIM_BUFFER  - s.POOL_NO_VICTIM_BUFFER,
        e.POOL_DRTY_PG_STEAL_CLNS       - s.POOL_DRTY_PG_STEAL_CLNS,

        --Direct IO

        e.DIRECT_READS          - s.DIRECT_READS,
        e.DIRECT_WRITES         - s.DIRECT_WRITES,
        e.DIRECT_READ_REQS      - s.DIRECT_READ_REQS,
        e.DIRECT_WRITE_REQS     - s.DIRECT_WRITE_REQS,

        --Sorting

        e.TOTAL_SORTS           - s.TOTAL_SORTS,
        e.SORT_OVERFLOWS  	- s.SORT_OVERFLOWS,
        e.TOTAL_SORT_TIME       - s.TOTAL_SORT_TIME,

        --Row Access

        e.ROWS_READ        	- s.ROWS_READ,
        e.ROWS_SELECTED 	- s.ROWS_SELECTED,
        e.PREFETCH_WAIT_TIME  	- s.PREFETCH_WAIT_TIME,

	e.ROWS_DELETED		- s.ROWS_DELETED,
	e.ROWS_INSERTED		- s.ROWS_INSERTED,
	e.ROWS_UPDATED		- s.ROWS_UPDATED,
	e.BINDS_PRECOMPILES	- s.BINDS_PRECOMPILES,
	e.APPL_SECTION_LOOKUPS	- s.APPL_SECTION_LOOKUPS,
	e.APPL_SECTION_INSERTS	- s.APPL_SECTION_INSERTS,
	e.CAT_CACHE_LOOKUPS	- s.CAT_CACHE_LOOKUPS,
	e.CAT_CACHE_INSERTS	- s.CAT_CACHE_INSERTS,
	e.CAT_CACHE_OVERFLOWS	- s.CAT_CACHE_OVERFLOWS,
	e.TOTAL_HASH_JOINS	- s.TOTAL_HASH_JOINS,
	e.TOTAL_HASH_LOOPS	- s.TOTAL_HASH_LOOPS,
	e.HASH_JOIN_OVERFLOWS	- s.HASH_JOIN_OVERFLOWS,
	e.HASH_JOIN_SMALL_OVERFLOWS	- s.HASH_JOIN_SMALL_OVERFLOWS,
	e.TOTAL_OLAP_FUNCS	- s.TOTAL_OLAP_FUNCS,
	e.OLAP_FUNC_OVERFLOWS	- s.OLAP_FUNC_OVERFLOWS,

        --PACKAGE ACCESS


        e.PKG_CACHE_LOOKUPS  	-  s.PKG_CACHE_LOOKUPS,
        e.PKG_CACHE_INSERTS   	-  s.PKG_CACHE_INSERTS,

        --Log Writing Activity

        e.LOG_WRITES                   	- s.LOG_WRITES,
        e.LOG_WRITE_TIME_S             	- s.LOG_WRITE_TIME_S,
        e.LOG_WRITE_TIME_NS            	- s.LOG_WRITE_TIME_NS,
        e.NUM_LOG_WRITE_IO             	- s.NUM_LOG_WRITE_IO,
        e.NUM_LOG_READ_IO              	- s.NUM_LOG_READ_IO,
        e.NUM_LOG_PART_PAGE_IO      	- s.NUM_LOG_PART_PAGE_IO,
        e.NUM_LOG_BUFFER_FULL  		- s.NUM_LOG_BUFFER_FULL,
        e.LOG_HELD_BY_DIRTY_PAGES,  	-- this is a point in time value, not a cumulative counter.

	--17May13, other related log info
	--17May13, other related log info
	e.LOG_READS		- s.LOG_READS,	--Number of log pages read from disk by logger.
	e.LOG_READ_TIME_S	- s.LOG_READ_TIME_S,	-- time spent reading log data from disk.
	e.LOG_READ_TIME_NS	- s.LOG_READ_TIME_NS,
	e.NUM_LOG_DATA_FOUND_IN_BUFFER 
				- s.NUM_LOG_DATA_FOUND_IN_BUFFER,
					--nbr of reads by agents from log buffer (not disk).
	e.APPL_ID_OLDEST_XACT,		--app/agentid of oldest trn.
	e.LOG_TO_REDO_FOR_RECOVERY,	--number of LOG bytes to REDO for crash recovery.

	e.STATS_CACHE_SIZE,
	e.STATS_FABRICATIONS 	- s.STATS_FABRICATIONS,
	e.SYNC_RUNSTATS 	- s.SYNC_RUNSTATS,
	e.ASYNC_RUNSTATS 	- s.ASYNC_RUNSTATS,
	e.STATS_FABRICATE_TIME	- s.STATS_FABRICATE_TIME, --msecs
	e.SYNC_RUNSTATS_TIME	- s.SYNC_RUNSTATS_TIME,   --msecs
	e.NUM_THRESHOLD_VIOLATIONS - s.NUM_THRESHOLD_VIOLATIONS
FROM
        dbmon.dubperf_DB_start s, dbmon.dubperf_DB_end e
WHERE
		s.DB_NAME = e.DB_NAME 
	AND 	s.DB_PATH = e.DB_PATH
	AND 	s.INPUT_DB_ALIAS = e.INPUT_DB_ALIAS
	AND 	s.DBPARTITIONNUM = e.DBPARTITIONNUM
;
UPDATE dbmon.dubperf_DB_diff
	SET  DURATION_SECS_TOTAL	
	= DURATION_DAYS * 24 * 60 * 60
	+ DURATION_HOURS * 60 * 60
	+ DURATION_MINS * 60
	+ DURATION_SECS
--where need to update for all entries
--	DBPARTITIONNUM=0
;

ECHO ******************************************;
ECHO GENERATING DUBPERF_MONTABLESPACE DIFF DATA;
ECHO ******************************************;
-- APR-MAY 2015
INSERT INTO DBMON.DUBPERF_MONTABLESPACE_DIFF
(
	START_TIMESTAMP 	,
	END_TIMESTAMP 		,

	DURATION_DAYS  		,
	DURATION_HOURS 		,
	DURATION_MINS  		,
	DURATION_SECS  		,
	DURATION_USECS 		,

	TBSP_NAME		,
	TBSP_ID 		,
	MEMBER 			,
	TBSP_TYPE 		,
	TBSP_CONTENT_TYPE 	,
	TBSP_STATE_START	,
	TBSP_STATE_END		,
	TBSP_PAGE_SIZE		,
	TBSP_EXTENT_SIZE	,
	TBSP_PREFETCH_SIZE	,
	TBSP_REBALANCER_MODE	,
	TBSP_USING_AUTO_STORAGE	,
	TBSP_AUTO_RESIZE_ENABLED,

	DIRECT_READS		,
	DIRECT_READ_REQS	,
	DIRECT_WRITES		,
	DIRECT_WRITE_REQS	,

	POOL_DATA_L_READS	,
	POOL_TEMP_DATA_L_READS	,
	POOL_XDA_L_READS	,
	POOL_TEMP_XDA_L_READS	,
	POOL_INDEX_L_READS	,
	POOL_TEMP_INDEX_L_READS	,
	POOL_DATA_P_READS	,
	POOL_TEMP_DATA_P_READS	,
	POOL_XDA_P_READS	,
	POOL_TEMP_XDA_P_READS	,
	POOL_INDEX_P_READS	,
	POOL_TEMP_INDEX_P_READS	,
	POOL_DATA_WRITES	,
	POOL_XDA_WRITES		,
	POOL_INDEX_WRITES	,

	DIRECT_READ_TIME	,
	DIRECT_WRITE_TIME	,
	POOL_READ_TIME		,
	POOL_WRITE_TIME		,

	POOL_ASYNC_DATA_READS	,
	POOL_ASYNC_DATA_READ_REQS	,
	POOL_ASYNC_DATA_WRITES		,
	POOL_ASYNC_INDEX_READS		,
	POOL_ASYNC_INDEX_READ_REQS	,
	POOL_ASYNC_INDEX_WRITES		,
	POOL_ASYNC_XDA_READS		,
	POOL_ASYNC_XDA_READ_REQS	,
	POOL_ASYNC_XDA_WRITES	,

	VECTORED_IOS		,
	PAGES_FROM_VECTORED_IOS	,
	BLOCK_IOS		,
	PAGES_FROM_BLOCK_IOS	,
	UNREAD_PREFETCH_PAGES	,
	FILES_CLOSED		,

	TBSP_USED_PAGES_DMS_START	,
	TBSP_USED_PAGES_DMS_END		,
	TBSP_FREE_PAGES_DMS_START	,
	TBSP_FREE_PAGES_DMS_END		,
	TBSP_USABLE_PAGES_DMS_START	,
	TBSP_USABLE_PAGES_DMS_END	,

	TBSP_TOTAL_PAGES_START	,
	TBSP_TOTAL_PAGES_END	,
	TBSP_PENDING_FREE_PAGES_DMS_START	,
	TBSP_PENDING_FREE_PAGES_DMS_END	,
	TBSP_PAGE_TOP_DMS_START		,--THIS IS A CURRENT WATERMARK, NOT TOP AS IT CAN SHRINK
	TBSP_PAGE_TOP_DMS_END		,
	TBSP_MAX_PAGE_TOP_DMS_START	,--HIGHEST PAGE NBR WATERMARK.
	TBSP_MAX_PAGE_TOP_DMS_END	,

	RECLAIMABLE_SPACE_ENABLED,
	AUTO_STORAGE_HYBRID	,
	TBSP_PATHS_DROPPED	,
	POOL_ASYNC_READ_TIME	,
	POOL_ASYNC_WRITE_TIME	,
	STORAGE_GROUP_NAME	,
	STORAGE_GROUP_ID	,
	PREFETCH_WAIT_TIME	,
	PREFETCH_WAITS	,

	-- 05jun15 Adding on bits missed and pool/prefetch not related to purescale
	TABLESPACE_MIN_RECOVERY_TIME,
	TBSP_TRACKMOD_STATE  	  	        ,
	TBSP_DATATAG				,
	
	POOL_QUEUED_ASYNC_DATA_REQS		,
	POOL_QUEUED_ASYNC_INDEX_REQS		,

	POOL_QUEUED_ASYNC_TEMP_DATA_REQS	,
	POOL_QUEUED_ASYNC_TEMP_INDEX_REQS	,
	POOL_QUEUED_ASYNC_TEMP_XDA_REQS		,
	POOL_QUEUED_ASYNC_OTHER_REQS		,

	POOL_QUEUED_ASYNC_DATA_PAGES		,
	POOL_QUEUED_ASYNC_INDEX_PAGES		,
	POOL_QUEUED_ASYNC_XDA_REQS		,
	POOL_QUEUED_ASYNC_XDA_PAGES		,

	POOL_QUEUED_ASYNC_TEMP_DATA_PAGES		,
	POOL_QUEUED_ASYNC_TEMP_INDEX_PAGES		,
	POOL_QUEUED_ASYNC_TEMP_XDA_PAGES		,

	POOL_FAILED_ASYNC_DATA_REQS		,
	POOL_FAILED_ASYNC_INDEX_REQS		,
	POOL_FAILED_ASYNC_XDA_REQS		,

	POOL_FAILED_ASYNC_TEMP_DATA_REQS			,
	POOL_FAILED_ASYNC_TEMP_INDEX_REQS			,
	POOL_FAILED_ASYNC_TEMP_XDA_REQS			,
	POOL_FAILED_ASYNC_OTHER_REQS			,

	SKIPPED_PREFETCH_DATA_P_READS		,
	SKIPPED_PREFETCH_INDEX_P_READS		,
	SKIPPED_PREFETCH_XDA_P_READS		,

	SKIPPED_PREFETCH_TEMP_DATA_P_READS		,
	SKIPPED_PREFETCH_TEMP_INDEX_P_READS		,
	SKIPPED_PREFETCH_TEMP_XDA_P_READS		,

	SKIPPED_PREFETCH_UOW_DATA_P_READS		,
	SKIPPED_PREFETCH_UOW_INDEX_P_READS		,
	SKIPPED_PREFETCH_UOW_XDA_P_READS		,

	SKIPPED_PREFETCH_UOW_TEMP_DATA_P_READS		,
	SKIPPED_PREFETCH_UOW_TEMP_INDEX_P_READS		,
	SKIPPED_PREFETCH_UOW_TEMP_XDA_P_READS		

)
SELECT
	s.START_TIMESTAMP,
	e.END_TIMESTAMP,

	DAY    (e.END_TIMESTAMP - s.START_TIMESTAMP),
	HOUR   (e.END_TIMESTAMP - s.START_TIMESTAMP),
	MINUTE (e.END_TIMESTAMP - s.START_TIMESTAMP),
	SECOND (e.END_TIMESTAMP - s.START_TIMESTAMP),
	MICROSECOND (e.END_TIMESTAMP - s.START_TIMESTAMP),

	s.TBSP_NAME		,
	s.TBSP_ID 		,
	s.MEMBER 		,
	s.TBSP_TYPE 		,
	s.TBSP_CONTENT_TYPE 	,
	s.TBSP_STATE		,
	e.TBSP_STATE		, -- ADDED this on 27May15
	s.TBSP_PAGE_SIZE	,
	s.TBSP_EXTENT_SIZE	,
	s.TBSP_PREFETCH_SIZE	,
	s.TBSP_REBALANCER_MODE	,
	s.TBSP_USING_AUTO_STORAGE	,
	s.TBSP_AUTO_RESIZE_ENABLED	,

	e.DIRECT_READS			- s.DIRECT_READS	,
	e.DIRECT_READ_REQS		- s.DIRECT_READ_REQS	,
	e.DIRECT_WRITES			- s.DIRECT_WRITES	,
	e.DIRECT_WRITE_REQS		- s.DIRECT_WRITE_REQS	,

	e.POOL_DATA_L_READS		- s.POOL_DATA_L_READS	,
	e.POOL_TEMP_DATA_L_READS	- s.POOL_TEMP_DATA_L_READS,
	e.POOL_XDA_L_READS		- s.POOL_XDA_L_READS	,
	e.POOL_TEMP_XDA_L_READS		- s.POOL_TEMP_XDA_L_READS,
	e.POOL_INDEX_L_READS		- s.POOL_INDEX_L_READS	,
	e.POOL_TEMP_INDEX_L_READS	- s.POOL_TEMP_INDEX_L_READS,
	e.POOL_DATA_P_READS		- s.POOL_DATA_P_READS	,
	e.POOL_TEMP_DATA_P_READS	- s.POOL_TEMP_DATA_P_READS,
	e.POOL_XDA_P_READS		- s.POOL_XDA_P_READS	,
	e.POOL_TEMP_XDA_P_READS		- s.POOL_TEMP_XDA_P_READS,
	e.POOL_INDEX_P_READS		- s.POOL_INDEX_P_READS	,
	e.POOL_TEMP_INDEX_P_READS	- s.POOL_TEMP_INDEX_P_READS,
	e.POOL_DATA_WRITES		- s.POOL_DATA_WRITES	,
	e.POOL_XDA_WRITES		- s.POOL_XDA_WRITES	,
	e.POOL_INDEX_WRITES		- s.POOL_INDEX_WRITES	,

	e.DIRECT_READ_TIME		- s.DIRECT_READ_TIME	,
	e.DIRECT_WRITE_TIME		- s.DIRECT_WRITE_TIME	,
	e.POOL_READ_TIME		- s.POOL_READ_TIME	,
	e.POOL_WRITE_TIME		- s.POOL_WRITE_TIME	,

	e.POOL_ASYNC_DATA_READS		- s.POOL_ASYNC_DATA_READS,
	e.POOL_ASYNC_DATA_READ_REQS	- s.POOL_ASYNC_DATA_READ_REQS	,
	e.POOL_ASYNC_DATA_WRITES	- s.POOL_ASYNC_DATA_WRITES	,
	e.POOL_ASYNC_INDEX_READS	- s.POOL_ASYNC_INDEX_READS	,
	e.POOL_ASYNC_INDEX_READ_REQS	- s.POOL_ASYNC_INDEX_READ_REQS	,
	e.POOL_ASYNC_INDEX_WRITES	- s.POOL_ASYNC_INDEX_WRITES	,
	e.POOL_ASYNC_XDA_READS		- s.POOL_ASYNC_XDA_READS	,
	e.POOL_ASYNC_XDA_READ_REQS	- s.POOL_ASYNC_XDA_READ_REQS	,
	e.POOL_ASYNC_XDA_WRITES		- s.POOL_ASYNC_XDA_WRITES	,
	e.VECTORED_IOS		  	- s.VECTORED_IOS		,
	e.PAGES_FROM_VECTORED_IOS	- s.PAGES_FROM_VECTORED_IOS	,
	e.BLOCK_IOS			- s.BLOCK_IOS			,
	e.PAGES_FROM_BLOCK_IOS		- s.PAGES_FROM_BLOCK_IOS	,
	e.UNREAD_PREFETCH_PAGES		- s.UNREAD_PREFETCH_PAGES	,
	e.FILES_CLOSED			- s.FILES_CLOSED		,

	s.TBSP_USED_PAGES	,
	e.TBSP_USED_PAGES	,
	s.TBSP_FREE_PAGES	,
	e.TBSP_FREE_PAGES	,
	s.TBSP_USABLE_PAGES	,
	e.TBSP_USABLE_PAGES	,
	s.TBSP_TOTAL_PAGES	,
	e.TBSP_TOTAL_PAGES	,
	s.TBSP_PENDING_FREE_PAGES,
	e.TBSP_PENDING_FREE_PAGES,
	s.TBSP_PAGE_TOP		,--THIS IS A CURRENT WATERMARK, NOT TOP AS IT CAN SHRINK
	e.TBSP_PAGE_TOP		,
	s.TBSP_MAX_PAGE_TOP	,--HIGHEST PAGE NBR WATERMARK.
	e.TBSP_MAX_PAGE_TOP	,

	s.RECLAIMABLE_SPACE_ENABLED	,
	e.AUTO_STORAGE_HYBRID		,
	e.TBSP_PATHS_DROPPED		,
--	e.TBSP_MIN_RECOVERYtIME,
	e.POOL_ASYNC_READ_TIME		- s.POOL_ASYNC_READ_TIME	,--MSECS
	e.POOL_ASYNC_WRITE_TIME		- s.POOL_ASYNC_WRITE_TIME	,--MSECS
	e.STORAGE_GROUP_NAME		,
	e.STORAGE_GROUP_ID		,
	e.PREFETCH_WAIT_TIME		- s.PREFETCH_WAIT_TIME	,
	e.PREFETCH_WAITS		- s.PREFETCH_WAITS,	

	-- 05jun15 Adding on bits missed and pool/prefetch not related to purescale
	E.TABLESPACE_MIN_RECOVERY_TIME,
	e.TBSP_TRACKMOD_STATE  	  	        ,
	e.TBSP_DATATAG				,
	
	e.POOL_QUEUED_ASYNC_DATA_REQS		- s.POOL_QUEUED_ASYNC_DATA_REQS		,
	e.POOL_QUEUED_ASYNC_INDEX_REQS		- s.POOL_QUEUED_ASYNC_INDEX_REQS,

	e.POOL_QUEUED_ASYNC_TEMP_DATA_REQS	- s.POOL_QUEUED_ASYNC_TEMP_DATA_REQS,
	e.POOL_QUEUED_ASYNC_TEMP_INDEX_REQS	- s.POOL_QUEUED_ASYNC_TEMP_INDEX_REQS,
	e.POOL_QUEUED_ASYNC_TEMP_XDA_REQS	- s.POOL_QUEUED_ASYNC_TEMP_XDA_REQS,
	e.POOL_QUEUED_ASYNC_OTHER_REQS		- s.POOL_QUEUED_ASYNC_OTHER_REQS,

	e.POOL_QUEUED_ASYNC_DATA_PAGES		- s.POOL_QUEUED_ASYNC_DATA_PAGES,
	e.POOL_QUEUED_ASYNC_INDEX_PAGES		- s.POOL_QUEUED_ASYNC_INDEX_REQS,
	e.POOL_QUEUED_ASYNC_XDA_REQS		- s.POOL_QUEUED_ASYNC_XDA_REQS,
	e.POOL_QUEUED_ASYNC_XDA_PAGES		- s.POOL_QUEUED_ASYNC_XDA_PAGES,

	e.POOL_QUEUED_ASYNC_TEMP_DATA_PAGES	- s.POOL_QUEUED_ASYNC_TEMP_DATA_PAGES,
	e.POOL_QUEUED_ASYNC_TEMP_INDEX_PAGES	- s.POOL_QUEUED_ASYNC_TEMP_INDEX_PAGES,
	e.POOL_QUEUED_ASYNC_TEMP_XDA_PAGES	- s.POOL_QUEUED_ASYNC_TEMP_XDA_PAGES,

	e.POOL_FAILED_ASYNC_DATA_REQS		- s.POOL_FAILED_ASYNC_DATA_REQS,
	e.POOL_FAILED_ASYNC_INDEX_REQS		- s.POOL_FAILED_ASYNC_INDEX_REQS,
	e.POOL_FAILED_ASYNC_XDA_REQS		- s.POOL_FAILED_ASYNC_XDA_REQS,

	e.POOL_FAILED_ASYNC_TEMP_DATA_REQS	- s.POOL_FAILED_ASYNC_TEMP_DATA_REQS,
	e.POOL_FAILED_ASYNC_TEMP_INDEX_REQS	- s.POOL_FAILED_ASYNC_TEMP_INDEX_REQS,
	e.POOL_FAILED_ASYNC_TEMP_XDA_REQS	- s.POOL_FAILED_ASYNC_TEMP_XDA_REQS,
	e.POOL_FAILED_ASYNC_OTHER_REQS		- s.POOL_FAILED_ASYNC_OTHER_REQS,


	e.SKIPPED_PREFETCH_DATA_P_READS		- s.SKIPPED_PREFETCH_DATA_P_READS,
	e.SKIPPED_PREFETCH_INDEX_P_READS	- s.SKIPPED_PREFETCH_INDEX_P_READS,
	e.SKIPPED_PREFETCH_XDA_P_READS		- s.SKIPPED_PREFETCH_XDA_P_READS,

	e.SKIPPED_PREFETCH_TEMP_DATA_P_READS	- s.SKIPPED_PREFETCH_TEMP_DATA_P_READS,
	e.SKIPPED_PREFETCH_TEMP_INDEX_P_READS	- s.SKIPPED_PREFETCH_TEMP_INDEX_P_READS,
	e.SKIPPED_PREFETCH_TEMP_XDA_P_READS	- s.SKIPPED_PREFETCH_TEMP_XDA_P_READS,

	e.SKIPPED_PREFETCH_UOW_DATA_P_READS	- s.SKIPPED_PREFETCH_UOW_DATA_P_READS,
	e.SKIPPED_PREFETCH_UOW_INDEX_P_READS	- s.SKIPPED_PREFETCH_UOW_INDEX_P_READS,
	e.SKIPPED_PREFETCH_UOW_XDA_P_READS	- s.SKIPPED_PREFETCH_UOW_XDA_P_READS,

	e.SKIPPED_PREFETCH_UOW_TEMP_DATA_P_READS  - s.SKIPPED_PREFETCH_UOW_TEMP_DATA_P_READS,
	e.SKIPPED_PREFETCH_UOW_TEMP_INDEX_P_READS	- s.SKIPPED_PREFETCH_UOW_TEMP_INDEX_P_READS,
	e.SKIPPED_PREFETCH_UOW_TEMP_XDA_P_READS		- s.SKIPPED_PREFETCH_UOW_TEMP_XDA_P_READS
	




FROM
 	DBMON.DUBPERF_MONTABLESPACE_START S
	FULL OUTER JOIN
--	,
	DBMON.DUBPERF_MONTABLESPACE_END   E
ON
--WHERE
	e.TBSP_ID	= s.TBSP_ID	
;
UPDATE DBMON.DUBPERF_MONTABLESPACE_DIFF
	SET  DURATION_SECS_TOTAL	
	= DURATION_DAYS * 24 * 60 * 60
	+ DURATION_HOURS * 60 * 60
	+ DURATION_MINS * 60
	+ DURATION_SECS
--where need to update for all entries
--	DBPARTITIONNUM=0
;

--COMMIT;
--QUIT;

ECHO ****************************************;
ECHO CAPTURING DUBPERF_MONCONTAINER DIFF DATA;
ECHO ****************************************;
INSERT INTO  DBMON.DUBPERF_MONCONTAINER_DIFF
(
	START_TIMESTAMP 	,
	END_TIMESTAMP 		,

	DURATION_DAYS  		,
	DURATION_HOURS 		,
	DURATION_MINS  		,
	DURATION_SECS  		,
	DURATION_USECS 		

	,TBSP_NAME 		
	,TBSP_ID 		
	,CONTAINER_NAME 		
	,CONTAINER_ID 		
	,MEMBER 			
	,CONTAINER_TYPE 		
	,STRIPE_SET 		


	,DIRECT_READS 		
	,DIRECT_WRITES 		
	,DIRECT_READ_TIME 	
	,DIRECT_WRITE_TIME 	
	,PAGES_READ 		
	,PAGES_WRITTEN 		
	,VECTORED_IOS 		
	,PAGES_FROM_VECTORED_IOS 
	,BLOCK_IOS 		
	,PAGES_FROM_BLOCK_IOS 	
	,POOL_READ_TIME 		
	,POOL_WRITE_TIME 	

	,TOTAL_PAGES 		
	,USABLE_PAGES 		
	,ACCESSIBLE 		
	,FS_ID 			
	,FS_TOTAL_SIZE 		
	,FS_USED_SIZE
)

SELECT
	S.START_TIMESTAMP,
	E.END_TIMESTAMP,

	DAY    (e.END_TIMESTAMP - s.START_TIMESTAMP),
	HOUR   (e.END_TIMESTAMP - s.START_TIMESTAMP),
	MINUTE (e.END_TIMESTAMP - s.START_TIMESTAMP),
	SECOND (e.END_TIMESTAMP - s.START_TIMESTAMP),
	MICROSECOND (e.END_TIMESTAMP - s.START_TIMESTAMP)

	,e.TBSP_NAME 		
	,e.TBSP_ID 		
	,e.CONTAINER_NAME 		
	,e.CONTAINER_ID 		
	,e.MEMBER 			
	,e.CONTAINER_TYPE 		
	,e.STRIPE_SET 		

	,e.DIRECT_READS 	- s.DIRECT_READS 		
	,e.DIRECT_WRITES 	- s.DIRECT_WRITES 		
	,e.DIRECT_READ_TIME	- s.DIRECT_READ_TIME 	
	,e.DIRECT_WRITE_TIME	- s.DIRECT_WRITE_TIME 	
	,e.PAGES_READ		- s.PAGES_READ 		
	,e.PAGES_WRITTEN	- s.PAGES_WRITTEN
	,e.VECTORED_IOS 	- s.VECTORED_IOS
	,e.PAGES_FROM_VECTORED_IOS	- s.PAGES_FROM_VECTORED_IOS 
	,e.BLOCK_IOS		- s.BLOCK_IOS 		
	,e.PAGES_FROM_BLOCK_IOS	- s.PAGES_FROM_BLOCK_IOS 	
	,e.POOL_READ_TIME	- s.POOL_READ_TIME
	,e.POOL_WRITE_TIME	- s.POOL_WRITE_TIME 	

	,e.TOTAL_PAGES
	,e.USABLE_PAGES
	,e.ACCESSIBLE
	,e.FS_ID
	,e.FS_TOTAL_SIZE
	,e.FS_USED_SIZE


FROM
 	DBMON.DUBPERF_MONCONTAINER_START S
	FULL OUTER JOIN
--	,
	DBMON.DUBPERF_MONCONTAINER_END   E
ON
--WHERE
	e.CONTAINER_ID	= s.CONTAINER_ID	
	AND e.MEMBER	= s.MEMBER
	AND e.TBSP_ID	= s.TBSP_ID
	AND e.FS_ID		= s.FS_ID
	AND e.TBSP_NAME 	= s.TBSP_NAME 		
	AND e.CONTAINER_NAME= s.CONTAINER_NAME
	AND e.CONTAINER_TYPE= s.CONTAINER_TYPE

;

UPDATE DBMON.DUBPERF_MONCONTAINER_DIFF
	SET  DURATION_SECS_TOTAL	
	= DURATION_DAYS * 24 * 60 * 60
	+ DURATION_HOURS * 60 * 60
	+ DURATION_MINS * 60
	+ DURATION_SECS
;
COMMIT;


ECHO ****************************************;
ECHO CAPTURING DUBPERF_MONINDEX DIFF DATA;
ECHO ****************************************;
INSERT INTO  DBMON.DUBPERF_MONINDEX_DIFF
(
	START_TIMESTAMP 	,
	END_TIMESTAMP 		,

	DURATION_DAYS  		,
	DURATION_HOURS 		,
	DURATION_MINS  		,
	DURATION_SECS  		,
	DURATION_USECS 		,

	TABSCHEMA 		,
	TABNAME 		,
	IID 			,
	MEMBER 			,
	DATA_PARTITION_ID 	,
	NLEAF 			,
	NLEVELS 		,
	INDEX_SCANS 		,
	INDEX_ONLY_SCANS 	,
	KEY_UPDATES 		,
	INCLUDE_COL_UPDATES 	,
	PSEUDO_DELETES 		,
	DEL_KEYS_CLEANED 	,
	ROOT_NODE_SPLITS 	,
	INT_NODE_SPLITS		,
	BOUNDARY_LEAF_NODE_SPLITS,
	NONBOUNDARY_LEAF_NODE_SPLITS,
	PAGE_ALLOCATIONS 	,
	PSEUDO_EMPTY_PAGES 	,
	EMPTY_PAGES_REUSED 	,
	EMPTY_PAGES_DELETED 	,
	PAGES_MERGED 		
)

SELECT
	S.SNAP_TIMESTAMP,
	E.SNAP_TIMESTAMP,

	DAY    (e.SNAP_TIMESTAMP - s.SNAP_TIMESTAMP),
	HOUR   (e.SNAP_TIMESTAMP - s.SNAP_TIMESTAMP),
	MINUTE (e.SNAP_TIMESTAMP - s.SNAP_TIMESTAMP),
	SECOND (e.SNAP_TIMESTAMP - s.SNAP_TIMESTAMP),
	MICROSECOND (e.SNAP_TIMESTAMP - s.SNAP_TIMESTAMP),

	E.TABSCHEMA	,
      	E.TABNAME	,
	E.IID 		,
	E.MEMBER 	,
	E.DATA_PARTITION_ID ,

	E.NLEAF 		, -- NBR OF LEAF LEVELS COUNTED SINCE STARTQUP
	E.NLEVELS 		, -- NBR OF INDEX COUNTED SINCE STARTUP

	E.INDEX_SCANS 		- S.INDEX_SCANS		,
	E.INDEX_ONLY_SCANS 	- S.INDEX_ONLY_SCANS 	,
	E.KEY_UPDATES 		- S.KEY_UPDATES	,
	E.INCLUDE_COL_UPDATES 	- S.INCLUDE_COL_UPDATES	,
	E.PSEUDO_DELETES 	- S.PSEUDO_DELETES 	,
	E.DEL_KEYS_CLEANED 	- S.DEL_KEYS_CLEANED 	,
	E.ROOT_NODE_SPLITS 	- S.ROOT_NODE_SPLITS 	,
	E.INT_NODE_SPLITS	- S.INT_NODE_SPLITS	,
	E.BOUNDARY_LEAF_NODE_SPLITS
				- S.BOUNDARY_LEAF_NODE_SPLITS,
	E.NONBOUNDARY_LEAF_NODE_SPLITS
				- S.NONBOUNDARY_LEAF_NODE_SPLITS,
	E.PAGE_ALLOCATIONS 	 -- NBR PAGES ALLOCATED TO INDEX
		- S.PAGE_ALLOCATIONS,
	E.PSEUDO_EMPTY_PAGES 	 -- NBR PAGES WITH ALL KEYS PSEUDO DELETED
		- S.PSEUDO_EMPTY_PAGES,
	E.EMPTY_PAGES_REUSED	- S.EMPTY_PAGES_REUSED 	,
	E.EMPTY_PAGES_DELETED	- S.EMPTY_PAGES_DELETED	,
	E.PAGES_MERGED		- S.PAGES_MERGED

FROM
 	DBMON.DUBPERF_MONINDEX_START S
	FULL OUTER JOIN
--	,
	DBMON.DUBPERF_MONINDEX_END   E
ON
--WHERE
	E.IID = S.IID
	AND E.MEMBER 	= S.MEMBER
	AND E.TABSCHEMA	= S.TABSCHEMA
	AND E.TABNAME 	= S.TABNAME
	AND (E.DATA_PARTITION_ID IS NULL -- either both sides are NULL or NOT NULL.
		OR 
		( (E.DATA_PARTITION_ID IS NOT NULL )
			AND (E.DATA_PARTITION_ID = S.DATA_PARTITION_ID)
		)
	    )
		
;

UPDATE DBMON.DUBPERF_MONINDEX_DIFF
	SET  DURATION_SECS_TOTAL	
	= DURATION_DAYS * 24 * 60 * 60
	+ DURATION_HOURS * 60 * 60
	+ DURATION_MINS * 60
	+ DURATION_SECS
;
COMMIT;

ECHO ****************************************;
ECHO CAPTURING DUBPERF_MONTABLE DIFF DATA;
ECHO ****************************************;

INSERT INTO  DBMON.DUBPERF_MONTABLE_DIFF
(
	START_TIMESTAMP 	,
	END_TIMESTAMP 		,

	DURATION_DAYS  		,
	DURATION_HOURS 		,
	DURATION_MINS  		,
	DURATION_SECS  		,
	DURATION_USECS 		,

	TABSCHEMA 		,
	TABNAME 		,
	MEMBER 			,
	TAB_TYPE 		,
	TAB_FILE_ID 		,
	DATA_PARTITION_ID 	,
	TBSP_ID 		,
	INDEX_TBSP_ID 		,
	LONG_TBSP_ID 		,
	TABLE_SCANS 		,
	ROWS_READ 		,
	ROWS_INSERTED 		,
	ROWS_UPDATED 		,
	ROWS_DELETED 		,
	OVERFLOW_ACCESSES 	,
	OVERFLOW_CREATES 	,
	PAGE_REORGS 		
)
SELECT 
	S.START_TIMESTAMP,
	E.END_TIMESTAMP,

	DAY    (e.END_TIMESTAMP - s.START_TIMESTAMP),
	HOUR   (e.END_TIMESTAMP - s.START_TIMESTAMP),
	MINUTE (e.END_TIMESTAMP - s.START_TIMESTAMP),
	SECOND (e.END_TIMESTAMP - s.START_TIMESTAMP),
	MICROSECOND (e.end_TIMESTAMP - s.START_TIMESTAMP),

	
	E.TABSCHEMA 		,
	E.TABNAME 		,
	E.MEMBER 		,
	E.TAB_TYPE 		,
	E.TAB_FILE_ID 		,
	E.DATA_PARTITION_ID 	,
	E.TBSP_ID 		,
	E.INDEX_TBSP_ID 	,
	E.LONG_TBSP_ID 		,

 	E.TABLE_SCANS 	- S.TABLE_SCANS		,
	E.ROWS_READ 	- S.ROWS_READ 		,
	E.ROWS_INSERTED - S.ROWS_INSERTED 		,
	E.ROWS_UPDATED 	- S.ROWS_UPDATED 		,
	E.ROWS_DELETED 	- S.ROWS_DELETED 		,
	E.OVERFLOW_ACCESSES 	- S.OVERFLOW_ACCESSES 	,
	E.OVERFLOW_CREATES 	- S.OVERFLOW_CREATES 	,
	E.PAGE_REORGS 	- S.PAGE_REORGS
FROM
	DBMON.DUBPERF_MONTABLE_START S
	FULL OUTER JOIN
	DBMON.DUBPERF_MONTABLE_END   E
	
ON
	E.TABSCHEMA	= S.TABSCHEMA
	AND E.TABNAME 	= S.TABNAME
	AND E.MEMBER 	= S.MEMBER
	AND E.TAB_TYPE	= S.TAB_TYPE
	AND E.TAB_FILE_ID	= S.TAB_FILE_ID
	AND E.TBSP_ID		= S.TBSP_ID
	AND E.INDEX_TBSP_ID 	= S.INDEX_TBSP_ID
	AND E.LONG_TBSP_ID	= S.LONG_TBSP_ID
--	AND E.DATA_PARTITION_ID	= s.DATA_PARTITION_ID
	
;
UPDATE DBMON.DUBPERF_MONTABLE_DIFF
	SET  DURATION_SECS_TOTAL	
	= DURATION_DAYS * 24 * 60 * 60
	+ DURATION_HOURS * 60 * 60
	+ DURATION_MINS * 60
	+ DURATION_SECS
;
COMMIT;
ECHO ****************************************;
ECHO END OF DUBPERF DIFF DATA CAPTURE;
ECHO ****************************************;
