-- Fergus (fergusmc@ie.ibm.com)
ECHO ************************************;
ECHO Creating DUBPERF_DB_Tables;
ECHO ************************************;
-- Create the 3 performance SNAPSHOT data tables
CREATE TABLE dbmon.dubperf_DB_start like sysibmadm.snapdb;
CREATE TABLE dbmon.dubperf_DB_end   like sysibmadm.snapdb;
CREATE TABLE dbmon.dubperf_DB_diff like sysibmadm.snapdb;
-- Add columns to the difference data to facilitate deriving the time difference between
-- the start and end snapshots
ALTER TABLE dbmon.dubperf_DB_diff RENAME COLUMN SNAPSHOT_TIMESTAMP TO END_TIMESTAMP;
ALTER TABLE dbmon.dubperf_DB_diff ADD    COLUMN START_TIMESTAMP TIMESTAMP;

ALTER TABLE dbmon.dubperf_DB_diff RENAME COLUMN  CONNECTIONS_TOP TO START_CONNECTIONS_TOP;
ALTER TABLE dbmon.dubperf_DB_diff ADD    COLUMN  END_CONNECTIONS_TOP BIGINT;

ALTER TABLE dbmon.dubperf_DB_diff RENAME COLUMN  APPLS_CUR_CONS  TO START_APPLS_CUR_CONS;
ALTER TABLE dbmon.dubperf_DB_diff ADD    COLUMN  END_APPLS_CUR_CONS BIGINT;
ALTER TABLE dbmon.dubperf_DB_diff RENAME COLUMN  APPLS_IN_DB2  TO START_APPLS_IN_DB;
ALTER TABLE dbmon.dubperf_DB_diff ADD    COLUMN  END_APPLS_IN_DB BIGINT;

ALTER TABLE dbmon.dubperf_DB_diff RENAME COLUMN  NUM_ASSOC_AGENTS  	TO	START_NUM_ASSOC_AGENTS;
ALTER TABLE dbmon.dubperf_DB_diff ADD    COLUMN  END_NUM_ASSOC_AGENTS 	BIGINT;

ALTER TABLE dbmon.dubperf_DB_diff RENAME COLUMN  AGENTS_TOP  		TO 	START_AGENTS_TOP;
ALTER TABLE dbmon.dubperf_DB_diff ADD    COLUMN  END_AGENTS_TOP 		BIGINT;

ALTER TABLE dbmon.dubperf_DB_diff RENAME COLUMN  COORD_AGENTS_TOP  	TO 	START_COORD_AGENTS_TOP;
ALTER TABLE dbmon.dubperf_DB_diff ADD    COLUMN  END_COORD_AGENTS_TOP 	BIGINT;



--ALTER TABLE dbmon.dubperf_DB_diff RENAME COLUMN   TO ;
--ALTER TABLE dbmon.dubperf_DB_diff ADD    COLUMN   BIGINT;

--ALTER TABLE dbmon.dubperf_DB_diff RENAME COLUMN  TO ;
--ALTER TABLE dbmon.dubperf_DB_diff ADD COLUMN ;


ALTER TABLE dbmon.dubperf_DB_diff ADD COLUMN DURATION_DAYS  INTEGER;
ALTER TABLE dbmon.dubperf_DB_diff ADD COLUMN DURATION_HOURS INTEGER;
ALTER TABLE dbmon.dubperf_DB_diff ADD COLUMN DURATION_MINS  INTEGER;
ALTER TABLE dbmon.dubperf_DB_diff ADD COLUMN DURATION_SECS  INTEGER;
ALTER TABLE dbmon.dubperf_DB_diff ADD COLUMN DURATION_USECS INTEGER;
ALTER TABLE dbmon.dubperf_DB_diff ADD COLUMN DURATION_SECS_TOTAL BIGINT;


ECHO ************************************************;
ECHO NEW MAR15: Creating DUBPERF_MONTABLESPACE Tables;
ECHO ************************************************;


CREATE TABLE DBMON.DUBPERF_MONTABLESPACE_START
(
	START_TIMESTAMP TIMESTAMP,

	TBSP_NAME 		VARCHAR(128),
	TBSP_ID 		BIGINT,
	MEMBER 			SMALLINT,
	TBSP_TYPE 		VARCHAR(10),
	TBSP_CONTENT_TYPE 	VARCHAR(10),
	TBSP_STATE		VARCHAR(256),

	TBSP_PAGE_SIZE		BIGINT,
	TBSP_EXTENT_SIZE	BIGINT,
	TBSP_PREFETCH_SIZE	BIGINT,
	TBSP_REBALANCER_MODE	VARCHAR(30),
	TBSP_USING_AUTO_STORAGE	SMALLINT,
	TBSP_AUTO_RESIZE_ENABLED	SMALLINT,

	DIRECT_READS		BIGINT,
	DIRECT_READ_REQS	BIGINT,
	DIRECT_WRITES		BIGINT,
	DIRECT_WRITE_REQS	BIGINT,

	POOL_DATA_L_READS	BIGINT,
	POOL_TEMP_DATA_L_READS	BIGINT,
	POOL_XDA_L_READS	BIGINT,
	POOL_TEMP_XDA_L_READS	BIGINT,
	POOL_INDEX_L_READS	BIGINT,
	POOL_TEMP_INDEX_L_READS	BIGINT,
	POOL_DATA_P_READS	BIGINT,
	POOL_TEMP_DATA_P_READS	BIGINT,
	POOL_XDA_P_READS	BIGINT,
	POOL_TEMP_XDA_P_READS	BIGINT,
	POOL_INDEX_P_READS	BIGINT,
	POOL_TEMP_INDEX_P_READS	BIGINT,
	POOL_DATA_WRITES	BIGINT,
	POOL_XDA_WRITES		BIGINT,
	POOL_INDEX_WRITES	BIGINT,

	DIRECT_READ_TIME	BIGINT,
	DIRECT_WRITE_TIME	BIGINT,
	POOL_READ_TIME		BIGINT,
	POOL_WRITE_TIME		BIGINT,

	POOL_ASYNC_DATA_READS	BIGINT,
	POOL_ASYNC_DATA_READ_REQS	BIGINT,
	POOL_ASYNC_DATA_WRITES		BIGINT,
	POOL_ASYNC_INDEX_READS		BIGINT,
	POOL_ASYNC_INDEX_READ_REQS	BIGINT,
	POOL_ASYNC_INDEX_WRITES		BIGINT,
	POOL_ASYNC_XDA_READS		BIGINT,
	POOL_ASYNC_XDA_READ_REQS	BIGINT,
	POOL_ASYNC_XDA_WRITES	BIGINT,

	VECTORED_IOS		BIGINT,
	PAGES_FROM_VECTORED_IOS	BIGINT,
	BLOCK_IOS		BIGINT,
	PAGES_FROM_BLOCK_IOS	BIGINT,
	UNREAD_PREFETCH_PAGES	BIGINT,
	FILES_CLOSED		BIGINT,

	TBSP_USED_PAGES		BIGINT,
	TBSP_FREE_PAGES		BIGINT,
	TBSP_USABLE_PAGES	BIGINT,

	TBSP_TOTAL_PAGES	BIGINT,
	TBSP_PENDING_FREE_PAGES	BIGINT,
	TBSP_PAGE_TOP		BIGINT,
	TBSP_MAX_PAGE_TOP	BIGINT,
	RECLAIMABLE_SPACE_ENABLED	SMALLINT,
	AUTO_STORAGE_HYBRID	SMALLINT,
	TBSP_PATHS_DROPPED	SMALLINT,
	POOL_ASYNC_READ_TIME			BIGINT,
	POOL_ASYNC_WRITE_TIME			BIGINT,
	STORAGE_GROUP_NAME			VARCHAR(128),
	STORAGE_GROUP_ID			INTEGER,

	PREFETCH_WAIT_TIME	BIGINT,
	PREFETCH_WAITS	BIGINT,

	-- 05jun15 Adding on bits missed and pool/prefetch not related to purescale
	TABLESPACE_MIN_RECOVERY_TIME    	  	     TIMESTAMP,
	TBSP_TRACKMOD_STATE  	  	        VARCHAR(32),
	TBSP_DATATAG				SMALLINT, --WLM DATA TAG
	
	POOL_QUEUED_ASYNC_DATA_REQS		BIGINT,
	POOL_QUEUED_ASYNC_INDEX_REQS		BIGINT,
	POOL_QUEUED_ASYNC_TEMP_DATA_REQS	BIGINT,
	POOL_QUEUED_ASYNC_TEMP_INDEX_REQS	BIGINT,
	POOL_QUEUED_ASYNC_TEMP_XDA_REQS		BIGINT,
	POOL_QUEUED_ASYNC_OTHER_REQS		BIGINT,

	POOL_QUEUED_ASYNC_DATA_PAGES		BIGINT,
	POOL_QUEUED_ASYNC_INDEX_PAGES		BIGINT,
	POOL_QUEUED_ASYNC_XDA_REQS		BIGINT,
	POOL_QUEUED_ASYNC_XDA_PAGES		BIGINT,

	POOL_QUEUED_ASYNC_TEMP_DATA_PAGES		BIGINT,
	POOL_QUEUED_ASYNC_TEMP_INDEX_PAGES		BIGINT,
	POOL_QUEUED_ASYNC_TEMP_XDA_PAGES		BIGINT,

	POOL_FAILED_ASYNC_DATA_REQS		BIGINT,
	POOL_FAILED_ASYNC_INDEX_REQS		BIGINT,
	POOL_FAILED_ASYNC_XDA_REQS		BIGINT,

	POOL_FAILED_ASYNC_TEMP_DATA_REQS			BIGINT,
	POOL_FAILED_ASYNC_TEMP_INDEX_REQS			BIGINT,
	POOL_FAILED_ASYNC_TEMP_XDA_REQS			BIGINT,
	POOL_FAILED_ASYNC_OTHER_REQS			BIGINT,

	SKIPPED_PREFETCH_DATA_P_READS		BIGINT,
	SKIPPED_PREFETCH_INDEX_P_READS		BIGINT,
	SKIPPED_PREFETCH_XDA_P_READS		BIGINT,

	SKIPPED_PREFETCH_TEMP_DATA_P_READS		BIGINT,
	SKIPPED_PREFETCH_TEMP_INDEX_P_READS		BIGINT,
	SKIPPED_PREFETCH_TEMP_XDA_P_READS		BIGINT,

	SKIPPED_PREFETCH_UOW_DATA_P_READS		BIGINT,
	SKIPPED_PREFETCH_UOW_INDEX_P_READS		BIGINT,
	SKIPPED_PREFETCH_UOW_XDA_P_READS		BIGINT,

	SKIPPED_PREFETCH_UOW_TEMP_DATA_P_READS		BIGINT,
	SKIPPED_PREFETCH_UOW_TEMP_INDEX_P_READS		BIGINT,
	SKIPPED_PREFETCH_UOW_TEMP_XDA_P_READS		BIGINT
	

);

CREATE TABLE DBMON.DUBPERF_MONTABLESPACE_END
(
	END_TIMESTAMP TIMESTAMP,

	TBSP_NAME 		VARCHAR(128),
	TBSP_ID 		BIGINT,
	MEMBER 			SMALLINT,
	TBSP_TYPE 		VARCHAR(10),
	TBSP_CONTENT_TYPE 	VARCHAR(10),
	TBSP_STATE		VARCHAR(256),

	TBSP_PAGE_SIZE		BIGINT,
	TBSP_EXTENT_SIZE	BIGINT,
	TBSP_PREFETCH_SIZE	BIGINT,
	TBSP_REBALANCER_MODE	VARCHAR(30),
	TBSP_USING_AUTO_STORAGE	SMALLINT,
	TBSP_AUTO_RESIZE_ENABLED	SMALLINT,

	DIRECT_READS		BIGINT,
	DIRECT_READ_REQS	BIGINT,
	DIRECT_WRITES		BIGINT,
	DIRECT_WRITE_REQS	BIGINT,

	POOL_DATA_L_READS	BIGINT,
	POOL_TEMP_DATA_L_READS	BIGINT,
	POOL_XDA_L_READS	BIGINT,
	POOL_TEMP_XDA_L_READS	BIGINT,
	POOL_INDEX_L_READS	BIGINT,
	POOL_TEMP_INDEX_L_READS	BIGINT,
	POOL_DATA_P_READS	BIGINT,
	POOL_TEMP_DATA_P_READS	BIGINT,
	POOL_XDA_P_READS	BIGINT,
	POOL_TEMP_XDA_P_READS	BIGINT,
	POOL_INDEX_P_READS	BIGINT,
	POOL_TEMP_INDEX_P_READS	BIGINT,
	POOL_DATA_WRITES	BIGINT,
	POOL_XDA_WRITES		BIGINT,
	POOL_INDEX_WRITES	BIGINT,

	DIRECT_READ_TIME	BIGINT,
	DIRECT_WRITE_TIME	BIGINT,
	POOL_READ_TIME		BIGINT,
	POOL_WRITE_TIME		BIGINT,

	POOL_ASYNC_DATA_READS	BIGINT,
	POOL_ASYNC_DATA_READ_REQS	BIGINT,
	POOL_ASYNC_DATA_WRITES		BIGINT,
	POOL_ASYNC_INDEX_READS		BIGINT,
	POOL_ASYNC_INDEX_READ_REQS	BIGINT,
	POOL_ASYNC_INDEX_WRITES		BIGINT,
	POOL_ASYNC_XDA_READS		BIGINT,
	POOL_ASYNC_XDA_READ_REQS	BIGINT,
	POOL_ASYNC_XDA_WRITES	BIGINT,
	VECTORED_IOS		BIGINT,
	PAGES_FROM_VECTORED_IOS	BIGINT,
	BLOCK_IOS		BIGINT,
	PAGES_FROM_BLOCK_IOS	BIGINT,
	UNREAD_PREFETCH_PAGES	BIGINT,
	FILES_CLOSED		BIGINT,
	TBSP_USED_PAGES		BIGINT,
	TBSP_FREE_PAGES		BIGINT,
	TBSP_USABLE_PAGES	BIGINT,
	TBSP_TOTAL_PAGES	BIGINT,
	TBSP_PENDING_FREE_PAGES	BIGINT,
	TBSP_PAGE_TOP		BIGINT,
	TBSP_MAX_PAGE_TOP	BIGINT,
	RECLAIMABLE_SPACE_ENABLED	SMALLINT,
	AUTO_STORAGE_HYBRID	SMALLINT,
	TBSP_PATHS_DROPPED	SMALLINT,
	POOL_ASYNC_READ_TIME			BIGINT,
	POOL_ASYNC_WRITE_TIME			BIGINT,
	STORAGE_GROUP_NAME			VARCHAR(128),
	STORAGE_GROUP_ID			INTEGER,

	PREFETCH_WAIT_TIME	BIGINT,
	PREFETCH_WAITS	BIGINT,

	-- 05jun15 Adding on bits missed and pool/prefetch not related to purescale
	TABLESPACE_MIN_RECOVERY_TIME    	  	     TIMESTAMP,
	TBSP_TRACKMOD_STATE  	  	        VARCHAR(32),
	TBSP_DATATAG				SMALLINT, --WLM DATA TAG
	
	POOL_QUEUED_ASYNC_DATA_REQS		BIGINT,
	POOL_QUEUED_ASYNC_INDEX_REQS		BIGINT,
	POOL_QUEUED_ASYNC_TEMP_DATA_REQS	BIGINT,
	POOL_QUEUED_ASYNC_TEMP_INDEX_REQS	BIGINT,
	POOL_QUEUED_ASYNC_TEMP_XDA_REQS		BIGINT,
	POOL_QUEUED_ASYNC_OTHER_REQS		BIGINT,
	POOL_QUEUED_ASYNC_DATA_PAGES		BIGINT,
	POOL_QUEUED_ASYNC_INDEX_PAGES		BIGINT,
	POOL_QUEUED_ASYNC_XDA_REQS		BIGINT,
	POOL_QUEUED_ASYNC_XDA_PAGES		BIGINT,	
	POOL_QUEUED_ASYNC_TEMP_DATA_PAGES		BIGINT,
	POOL_QUEUED_ASYNC_TEMP_INDEX_PAGES		BIGINT,
	POOL_QUEUED_ASYNC_TEMP_XDA_PAGES		BIGINT,

	POOL_FAILED_ASYNC_DATA_REQS		BIGINT,
	POOL_FAILED_ASYNC_INDEX_REQS		BIGINT,
	POOL_FAILED_ASYNC_XDA_REQS		BIGINT,
	POOL_FAILED_ASYNC_TEMP_DATA_REQS			BIGINT,
	POOL_FAILED_ASYNC_TEMP_INDEX_REQS			BIGINT,
	POOL_FAILED_ASYNC_TEMP_XDA_REQS			BIGINT,
	POOL_FAILED_ASYNC_OTHER_REQS			BIGINT,

	SKIPPED_PREFETCH_DATA_P_READS		BIGINT,
	SKIPPED_PREFETCH_INDEX_P_READS		BIGINT,
	SKIPPED_PREFETCH_XDA_P_READS		BIGINT,

	SKIPPED_PREFETCH_TEMP_DATA_P_READS		BIGINT,
	SKIPPED_PREFETCH_TEMP_INDEX_P_READS		BIGINT,
	SKIPPED_PREFETCH_TEMP_XDA_P_READS		BIGINT,

	SKIPPED_PREFETCH_UOW_DATA_P_READS		BIGINT,
	SKIPPED_PREFETCH_UOW_INDEX_P_READS		BIGINT,
	SKIPPED_PREFETCH_UOW_XDA_P_READS		BIGINT,

	SKIPPED_PREFETCH_UOW_TEMP_DATA_P_READS		BIGINT,
	SKIPPED_PREFETCH_UOW_TEMP_INDEX_P_READS		BIGINT,
	SKIPPED_PREFETCH_UOW_TEMP_XDA_P_READS		BIGINT

);

CREATE TABLE DBMON.DUBPERF_MONTABLESPACE_DIFF
(
	START_TIMESTAMP		TIMESTAMP,
	END_TIMESTAMP 		TIMESTAMP,
	DURATION_DAYS  		INTEGER,
	DURATION_HOURS 		INTEGER,
	DURATION_MINS  		INTEGER,
	DURATION_SECS  		INTEGER,
	DURATION_USECS 		INTEGER,
	DURATION_SECS_TOTAL 	BIGINT,

	TBSP_NAME 		VARCHAR(128),
	TBSP_ID 		BIGINT,
	MEMBER 			SMALLINT,
	TBSP_TYPE 		VARCHAR(10),
	TBSP_CONTENT_TYPE 	VARCHAR(10),
	TBSP_STATE_START		VARCHAR(256),
	TBSP_STATE_END		VARCHAR(256),

	TBSP_PAGE_SIZE		BIGINT,
	TBSP_EXTENT_SIZE	BIGINT,
	TBSP_PREFETCH_SIZE	BIGINT,
	TBSP_REBALANCER_MODE	VARCHAR(30),
	TBSP_USING_AUTO_STORAGE	SMALLINT,
	TBSP_AUTO_RESIZE_ENABLED	SMALLINT,

	DIRECT_READS		BIGINT,
	DIRECT_READ_REQS	BIGINT,
	DIRECT_WRITES		BIGINT,
	DIRECT_WRITE_REQS	BIGINT,

	POOL_DATA_L_READS	BIGINT,
	POOL_TEMP_DATA_L_READS	BIGINT,
	POOL_XDA_L_READS	BIGINT,
	POOL_TEMP_XDA_L_READS	BIGINT,
	POOL_INDEX_L_READS	BIGINT,
	POOL_TEMP_INDEX_L_READS	BIGINT,
	POOL_DATA_P_READS	BIGINT,
	POOL_TEMP_DATA_P_READS	BIGINT,
	POOL_XDA_P_READS	BIGINT,
	POOL_TEMP_XDA_P_READS	BIGINT,
	POOL_INDEX_P_READS	BIGINT,
	POOL_TEMP_INDEX_P_READS	BIGINT,
	POOL_DATA_WRITES	BIGINT,
	POOL_XDA_WRITES		BIGINT,
	POOL_INDEX_WRITES	BIGINT,

	DIRECT_READ_TIME	BIGINT,
	DIRECT_WRITE_TIME	BIGINT,
	POOL_READ_TIME		BIGINT,
	POOL_WRITE_TIME		BIGINT,

	POOL_ASYNC_DATA_READS	BIGINT,
	POOL_ASYNC_DATA_READ_REQS	BIGINT,
	POOL_ASYNC_DATA_WRITES		BIGINT,
	POOL_ASYNC_INDEX_READS		BIGINT,
	POOL_ASYNC_INDEX_READ_REQS	BIGINT,
	POOL_ASYNC_INDEX_WRITES		BIGINT,
	POOL_ASYNC_XDA_READS		BIGINT,
	POOL_ASYNC_XDA_READ_REQS	BIGINT,
	POOL_ASYNC_XDA_WRITES	BIGINT,

	VECTORED_IOS		BIGINT,
	PAGES_FROM_VECTORED_IOS	BIGINT,
	BLOCK_IOS		BIGINT,
	PAGES_FROM_BLOCK_IOS	BIGINT,
	UNREAD_PREFETCH_PAGES	BIGINT,
	FILES_CLOSED		BIGINT,

	TBSP_USED_PAGES_DMS_START	BIGINT,	
	TBSP_USED_PAGES_DMS_END		BIGINT,	
	TBSP_FREE_PAGES_DMS_START	BIGINT,
	TBSP_FREE_PAGES_DMS_END		BIGINT,
	TBSP_USABLE_PAGES_DMS_START	BIGINT,
	TBSP_USABLE_PAGES_DMS_END	BIGINT,

	TBSP_TOTAL_PAGES_START		BIGINT,
	TBSP_TOTAL_PAGES_END		BIGINT,
	TBSP_PENDING_FREE_PAGES_DMS_START	BIGINT,
	TBSP_PENDING_FREE_PAGES_DMS_END		BIGINT,
	TBSP_PAGE_TOP_DMS_START			BIGINT, --THIS IS A CURRENT WATERMARK, NOT TOP AS IT CAN SHRINK
	TBSP_PAGE_TOP_DMS_END			BIGINT,
	TBSP_MAX_PAGE_TOP_DMS_START		BIGINT, --HIGHEST PAGE NBR WATERMARK.
	TBSP_MAX_PAGE_TOP_DMS_END		BIGINT,

	RECLAIMABLE_SPACE_ENABLED	SMALLINT,
	AUTO_STORAGE_HYBRID	SMALLINT,
	TBSP_PATHS_DROPPED	SMALLINT,
	POOL_ASYNC_READ_TIME			BIGINT,
	POOL_ASYNC_WRITE_TIME			BIGINT,
	STORAGE_GROUP_NAME			VARCHAR(128),
	STORAGE_GROUP_ID			INTEGER,

	PREFETCH_WAIT_TIME			BIGINT,
	PREFETCH_WAITS				BIGINT,

	-- 05jun15 Adding on bits missed and pool/prefetch not related to purescale
	TABLESPACE_MIN_RECOVERY_TIME    	  	     TIMESTAMP,
	TBSP_TRACKMOD_STATE  	  	        VARCHAR(32),
	TBSP_DATATAG				SMALLINT, --WLM DATA TAG
	
	POOL_QUEUED_ASYNC_DATA_REQS		BIGINT,
	POOL_QUEUED_ASYNC_INDEX_REQS		BIGINT,

	POOL_QUEUED_ASYNC_TEMP_DATA_REQS	BIGINT,
	POOL_QUEUED_ASYNC_TEMP_INDEX_REQS	BIGINT,
	POOL_QUEUED_ASYNC_TEMP_XDA_REQS		BIGINT,
	POOL_QUEUED_ASYNC_OTHER_REQS		BIGINT,

	POOL_QUEUED_ASYNC_DATA_PAGES		BIGINT,
	POOL_QUEUED_ASYNC_INDEX_PAGES		BIGINT,
	POOL_QUEUED_ASYNC_XDA_REQS		BIGINT,
	POOL_QUEUED_ASYNC_XDA_PAGES		BIGINT,

	POOL_QUEUED_ASYNC_TEMP_DATA_PAGES		BIGINT,
	POOL_QUEUED_ASYNC_TEMP_INDEX_PAGES		BIGINT,
	POOL_QUEUED_ASYNC_TEMP_XDA_PAGES		BIGINT,

	POOL_FAILED_ASYNC_DATA_REQS		BIGINT,
	POOL_FAILED_ASYNC_INDEX_REQS		BIGINT,
	POOL_FAILED_ASYNC_XDA_REQS		BIGINT,

	POOL_FAILED_ASYNC_TEMP_DATA_REQS			BIGINT,
	POOL_FAILED_ASYNC_TEMP_INDEX_REQS			BIGINT,
	POOL_FAILED_ASYNC_TEMP_XDA_REQS			BIGINT,
	POOL_FAILED_ASYNC_OTHER_REQS			BIGINT,


	SKIPPED_PREFETCH_DATA_P_READS		BIGINT,
	SKIPPED_PREFETCH_INDEX_P_READS		BIGINT,
	SKIPPED_PREFETCH_XDA_P_READS		BIGINT,

	SKIPPED_PREFETCH_TEMP_DATA_P_READS		BIGINT,
	SKIPPED_PREFETCH_TEMP_INDEX_P_READS		BIGINT,
	SKIPPED_PREFETCH_TEMP_XDA_P_READS		BIGINT,

	SKIPPED_PREFETCH_UOW_DATA_P_READS		BIGINT,
	SKIPPED_PREFETCH_UOW_INDEX_P_READS		BIGINT,
	SKIPPED_PREFETCH_UOW_XDA_P_READS		BIGINT,

	SKIPPED_PREFETCH_UOW_TEMP_DATA_P_READS		BIGINT,
	SKIPPED_PREFETCH_UOW_TEMP_INDEX_P_READS		BIGINT,
	SKIPPED_PREFETCH_UOW_TEMP_XDA_P_READS		BIGINT
);

--COMMIT;
--QUIT;


ECHO ************************************;
ECHO Creating DUBPERF_MONCONTAINER Tables;
ECHO ************************************;


CREATE TABLE DBMON.DUBPERF_MONCONTAINER_START
(
	START_TIMESTAMP TIMESTAMP,
--	END_TIMESTAMP  TIMESTAMP,
--	DURATION_DAYS  INTEGERQ,
--	DURATION_HOURS INTEGER,
--	DURATION_MINS  INTEGER,
--	DURATION_SECS  INTEGER,
--	DURATION_USECS INTEGER,
--	DURATION_SECS_TOTAL BIGINT,

	TBSP_NAME 		VARCHAR(128),
	TBSP_ID 		BIGINT,
	CONTAINER_NAME 		VARCHAR(256),
	CONTAINER_ID 		BIGINT,
	MEMBER 			SMALLINT,
	CONTAINER_TYPE 		VARCHAR(16),
	STRIPE_SET 		BIGINT,
	DIRECT_READS 		BIGINT,
	DIRECT_WRITES 		BIGINT,
	DIRECT_READ_TIME 	BIGINT,
	DIRECT_WRITE_TIME 	BIGINT,
	PAGES_READ 		BIGINT,
	PAGES_WRITTEN 		BIGINT,
	VECTORED_IOS 		BIGINT,
	PAGES_FROM_VECTORED_IOS BIGINT,
	BLOCK_IOS 		BIGINT,
	PAGES_FROM_BLOCK_IOS 	BIGINT,
	POOL_READ_TIME 		BIGINT,
	POOL_WRITE_TIME 	BIGINT,
	TOTAL_PAGES 		BIGINT,
	USABLE_PAGES 		BIGINT,
	ACCESSIBLE 		SMALLINT,
	FS_ID 			VARCHAR(22),
	FS_TOTAL_SIZE 		BIGINT,
	FS_USED_SIZE BIGINT
--	,ADDITIONAL_DETAILS 	BLOB(0)
);

CREATE TABLE DBMON.DUBPERF_MONCONTAINER_END
(
--	START_TIMESTAMP TIMESTAMP,
	END_TIMESTAMP	TIMESTAMP,
--	DURATION_DAYS  	INTEGER,
--	DURATION_HOURS 	INTEGER,
--	DURATION_MINS  	INTEGER,
--	DURATION_SECS  	INTEGER,
--	DURATION_USECS 	INTEGER,
--	DURATION_SECS_TOTAL BIGINT,
	TBSP_NAME 		VARCHAR(128),
	TBSP_ID 		BIGINT,
	CONTAINER_NAME 		VARCHAR(256),
	CONTAINER_ID 		BIGINT,
	MEMBER 			SMALLINT,
	CONTAINER_TYPE 		VARCHAR(16),
	STRIPE_SET 		BIGINT,
	DIRECT_READS 		BIGINT,
	DIRECT_WRITES 		BIGINT,
	DIRECT_READ_TIME 	BIGINT,
	DIRECT_WRITE_TIME 	BIGINT,
	PAGES_READ 		BIGINT,
	PAGES_WRITTEN 		BIGINT,
	VECTORED_IOS 		BIGINT,
	PAGES_FROM_VECTORED_IOS BIGINT,
	BLOCK_IOS 		BIGINT,
	PAGES_FROM_BLOCK_IOS 	BIGINT,
	POOL_READ_TIME 		BIGINT,
	POOL_WRITE_TIME 	BIGINT,
	TOTAL_PAGES 		BIGINT,
	USABLE_PAGES 		BIGINT,
	ACCESSIBLE 		SMALLINT,
	FS_ID 			VARCHAR(22),
	FS_TOTAL_SIZE 		BIGINT,
	FS_USED_SIZE BIGINT


--	,ADDITIONAL_DETAILS 	BLOB(0)


);
CREATE TABLE DBMON.DUBPERF_MONCONTAINER_DIFF
(
	START_TIMESTAMP 	TIMESTAMP,
	END_TIMESTAMP  		TIMESTAMP,
	DURATION_DAYS  		INTEGER,
	DURATION_HOURS 		INTEGER,
	DURATION_MINS  		INTEGER,
	DURATION_SECS  		INTEGER,
	DURATION_USECS 		INTEGER,
	DURATION_SECS_TOTAL 	BIGINT,

	TBSP_NAME 		VARCHAR(128),
	TBSP_ID 		BIGINT,
	CONTAINER_NAME 		VARCHAR(256),
	CONTAINER_ID 		BIGINT,
	MEMBER 			SMALLINT,
	CONTAINER_TYPE 		VARCHAR(16),
	STRIPE_SET 		BIGINT,
	DIRECT_READS 		BIGINT,
	DIRECT_WRITES 		BIGINT,
	DIRECT_READ_TIME 	BIGINT,
	DIRECT_WRITE_TIME 	BIGINT,
	PAGES_READ 		BIGINT,
	PAGES_WRITTEN 		BIGINT,
	VECTORED_IOS 		BIGINT,
	PAGES_FROM_VECTORED_IOS BIGINT,
	BLOCK_IOS 		BIGINT,
	PAGES_FROM_BLOCK_IOS 	BIGINT,
	POOL_READ_TIME 		BIGINT,
	POOL_WRITE_TIME 	BIGINT,
	TOTAL_PAGES 		BIGINT,
	USABLE_PAGES 		BIGINT,
	ACCESSIBLE 		SMALLINT,
	FS_ID 			VARCHAR(22),
	FS_TOTAL_SIZE 		BIGINT,
	FS_USED_SIZE BIGINT

--	,ADDITIONAL_DETAILS 	BLOB(0)


);

COMMIT;



ECHO ************************************;
ECHO Creating DUBPERF_MONINDEX Tables;
ECHO ************************************;



CREATE TABLE DBMON.DUBPERF_MONINDEX_START
(
	
        SNAP_TIMESTAMP 	TIMESTAMP,
--      END_TIMESTAMP  TIMESTAMP,
--      DURATION_DAYS  INTEGER,
--      DURATION_HOURS INTEGER,
--      DURATION_MINS  INTEGER,
--      DURATION_SECS  INTEGER,
--      DURATION_USECS INTEGER,
--      DURATION_SECS_TOTAL BIGINT,

	TABSCHEMA 		VARCHAR(128),
	TABNAME 		VARCHAR(128),
	IID 			SMALLINT,
	MEMBER 			SMALLINT,
	DATA_PARTITION_ID 	INTEGER,
	NLEAF 			BIGINT,
	NLEVELS 		SMALLINT,
	INDEX_SCANS 		BIGINT,
	INDEX_ONLY_SCANS 	BIGINT,
	KEY_UPDATES 		BIGINT,
	INCLUDE_COL_UPDATES 	BIGINT,
	PSEUDO_DELETES 		BIGINT,
	DEL_KEYS_CLEANED 	BIGINT,
	ROOT_NODE_SPLITS 	BIGINT,
	INT_NODE_SPLITS 	BIGINT,
	BOUNDARY_LEAF_NODE_SPLITS 	BIGINT,
	NONBOUNDARY_LEAF_NODE_SPLITS 	BIGINT,
	PAGE_ALLOCATIONS 	BIGINT,
	PSEUDO_EMPTY_PAGES 	BIGINT,
	EMPTY_PAGES_REUSED 	BIGINT,
	EMPTY_PAGES_DELETED 	BIGINT,
	PAGES_MERGED 		BIGINT
--	,ADDITIONAL_DETAILS 	BLOB
)
;
CREATE TABLE DBMON.DUBPERF_MONINDEX_END
(
	
        SNAP_TIMESTAMP 	TIMESTAMP,
--      END_TIMESTAMP  TIMESTAMP,
--      DURATION_DAYS  INTEGER,
--      DURATION_HOURS INTEGER,
--      DURATION_MINS  INTEGER,
--      DURATION_SECS  INTEGER,
--      DURATION_USECS INTEGER,
--      DURATION_SECS_TOTAL BIGINT,

	TABSCHEMA 		VARCHAR(128),
	TABNAME 		VARCHAR(128),
	IID 			SMALLINT,
	MEMBER 			SMALLINT,
	DATA_PARTITION_ID 	INTEGER,
	NLEAF 			BIGINT,
	NLEVELS 		SMALLINT,
	INDEX_SCANS 		BIGINT,
	INDEX_ONLY_SCANS 	BIGINT,
	KEY_UPDATES 		BIGINT,
	INCLUDE_COL_UPDATES 	BIGINT,
	PSEUDO_DELETES 		BIGINT,
	DEL_KEYS_CLEANED 	BIGINT,
	ROOT_NODE_SPLITS 	BIGINT,
	INT_NODE_SPLITS 	BIGINT,
	BOUNDARY_LEAF_NODE_SPLITS 	BIGINT,
	NONBOUNDARY_LEAF_NODE_SPLITS 	BIGINT,
	PAGE_ALLOCATIONS 	BIGINT,
	PSEUDO_EMPTY_PAGES 	BIGINT,
	EMPTY_PAGES_REUSED 	BIGINT,
	EMPTY_PAGES_DELETED 	BIGINT,
	PAGES_MERGED 		BIGINT
--	,ADDITIONAL_DETAILS 	BLOB
)
;
CREATE TABLE DBMON.DUBPERF_MONINDEX_DIFF
(
	
        START_TIMESTAMP 	TIMESTAMP,
      	END_TIMESTAMP  TIMESTAMP,
      	DURATION_DAYS  INTEGER,
      	DURATION_HOURS INTEGER,
      	DURATION_MINS  INTEGER,
      	DURATION_SECS  INTEGER,
      	DURATION_USECS INTEGER,
      	DURATION_SECS_TOTAL BIGINT,

	TABSCHEMA 		VARCHAR(128),
	TABNAME 		VARCHAR(128),
	IID 			SMALLINT,
	MEMBER 			SMALLINT,
	DATA_PARTITION_ID 	INTEGER,
	NLEAF 			BIGINT,
	NLEVELS 		SMALLINT,
	INDEX_SCANS 		BIGINT,
	INDEX_ONLY_SCANS 	BIGINT,
	KEY_UPDATES 		BIGINT,
	INCLUDE_COL_UPDATES 	BIGINT,
	PSEUDO_DELETES 		BIGINT,
	DEL_KEYS_CLEANED 	BIGINT,
	ROOT_NODE_SPLITS 	BIGINT,
	INT_NODE_SPLITS 	BIGINT,
	BOUNDARY_LEAF_NODE_SPLITS 	BIGINT,
	NONBOUNDARY_LEAF_NODE_SPLITS 	BIGINT,
	PAGE_ALLOCATIONS 	BIGINT,
	PSEUDO_EMPTY_PAGES 	BIGINT,
	EMPTY_PAGES_REUSED 	BIGINT,
	EMPTY_PAGES_DELETED 	BIGINT,
	PAGES_MERGED 		BIGINT
--	,ADDITIONAL_DETAILS 	BLOB
)
;

COMMIT;

ECHO ************************************;
ECHO Creating DUBPERF_MONTABLE Tables;
ECHO ************************************;



CREATE TABLE DBMON.DUBPERF_MONTABLE_START
(
	START_TIMESTAMP TIMESTAMP,
--	END_TIMESTAMP  TIMESTAMP,
--	DURATION_DAYS  INTEGER,
--	DURATION_HOURS INTEGER,
--	DURATION_MINS  INTEGER,
--	DURATION_SECS  INTEGER,
--	DURATION_USECS INTEGER,
--	DURATION_SECS_TOTAL BIGINT,

	TABSCHEMA 		VARCHAR(128),
	TABNAME 		VARCHAR(128),
	MEMBER 			SMALLINT,
	TAB_TYPE 		VARCHAR(14),
	TAB_FILE_ID 		BIGINT,
	DATA_PARTITION_ID 	INTEGER,
	TBSP_ID 		BIGINT,
	INDEX_TBSP_ID 		BIGINT,
	LONG_TBSP_ID 		BIGINT,
	TABLE_SCANS 		BIGINT,
	ROWS_READ 		BIGINT,
	ROWS_INSERTED 		BIGINT,
	ROWS_UPDATED 		BIGINT,
	ROWS_DELETED 		BIGINT,
	OVERFLOW_ACCESSES 	BIGINT,
	OVERFLOW_CREATES 	BIGINT,
	PAGE_REORGS 		BIGINT
--	,ADDITIONAL_DETAILS 	BLOB(0)
);

CREATE TABLE DBMON.DUBPERF_MONTABLE_END
(
--	START_TIMESTAMP TIMESTAMP,
	END_TIMESTAMP	TIMESTAMP,
--	DURATION_DAYS  	INTEGER,
--	DURATION_HOURS 	INTEGER,
--	DURATION_MINS  	INTEGER,
--	DURATION_SECS  	INTEGER,
--	DURATION_USECS 	INTEGER,
--	DURATION_SECS_TOTAL BIGINT,

	TABSCHEMA 		VARCHAR(128),
	TABNAME 		VARCHAR(128),
	MEMBER 			SMALLINT,
	TAB_TYPE 		VARCHAR(14),
	TAB_FILE_ID 		BIGINT,
	DATA_PARTITION_ID 	INTEGER,
	TBSP_ID 		BIGINT,
	INDEX_TBSP_ID 		BIGINT,
	LONG_TBSP_ID 		BIGINT,
	TABLE_SCANS 		BIGINT,
	ROWS_READ 		BIGINT,
	ROWS_INSERTED 		BIGINT,
	ROWS_UPDATED 		BIGINT,
	ROWS_DELETED 		BIGINT,
	OVERFLOW_ACCESSES 	BIGINT,
	OVERFLOW_CREATES 	BIGINT,
	PAGE_REORGS 		BIGINT
--	,ADDITIONAL_DETAILS 	BLOB(0)


);
CREATE TABLE DBMON.DUBPERF_MONTABLE_DIFF
(
	START_TIMESTAMP 	TIMESTAMP,
	END_TIMESTAMP  		TIMESTAMP,
	DURATION_DAYS  		INTEGER,
	DURATION_HOURS 		INTEGER,
	DURATION_MINS  		INTEGER,
	DURATION_SECS  		INTEGER,
	DURATION_USECS 		INTEGER,
	DURATION_SECS_TOTAL 	BIGINT,

	TABSCHEMA 		VARCHAR(128),
	TABNAME 		VARCHAR(128),
	MEMBER 			SMALLINT,
	TAB_TYPE 		VARCHAR(14),
	TAB_FILE_ID 		BIGINT,
	DATA_PARTITION_ID 	INTEGER,
	TBSP_ID 		BIGINT,
	INDEX_TBSP_ID 		BIGINT,
	LONG_TBSP_ID 		BIGINT,
	TABLE_SCANS 		BIGINT,
	ROWS_READ 		BIGINT,
	ROWS_INSERTED 		BIGINT,
	ROWS_UPDATED 		BIGINT,
	ROWS_DELETED 		BIGINT,
	OVERFLOW_ACCESSES 	BIGINT,
	OVERFLOW_CREATES 	BIGINT,
	PAGE_REORGS 		BIGINT
--	,ADDITIONAL_DETAILS 	BLOB(0)


);

COMMIT;


ECHO ************************************;
ECHO END DUBPERF TABLE CREATION;
ECHO ************************************;




