-- Fergus (fergusmc@ie.ibm.com)
ECHO ************************************;
ECHO TAKING DUBPERF_DB START SNAPSHOT;
ECHO ************************************;
INSERT INTO DBMON.DUBPERF_DB_START SELECT * FROM SYSIBMADM.SNAPDB;

ECHO ************************************************;
ECHO NEW MAR15: Taking DUBPERF_MONTABLESPACE Snapshot;
ECHO ************************************************;

INSERT INTO DBMON.DUBPERF_MONTABLESPACE_START
(
	START_TIMESTAMP		,
	TBSP_NAME		,
	TBSP_ID 		,
	MEMBER 			,
	TBSP_TYPE 		,
	TBSP_CONTENT_TYPE 	,
	TBSP_STATE		,
	TBSP_PAGE_SIZE		,
	TBSP_EXTENT_SIZE	,
	TBSP_PREFETCH_SIZE	,
	TBSP_REBALANCER_MODE	,
	TBSP_USING_AUTO_STORAGE	,
	TBSP_AUTO_RESIZE_ENABLED,

	-- counters
	DIRECT_READS		,
	DIRECT_READ_REQS	,
	DIRECT_WRITES		,
	DIRECT_WRITE_REQS	,

	POOL_DATA_L_READS	,
	POOL_TEMP_DATA_L_READS	,
	POOL_XDA_L_READS	,
	POOL_TEMP_XDA_L_READS	,
	POOL_INDEX_L_READS	,
	POOL_TEMP_INDEX_L_READS	,
	POOL_DATA_P_READS	,
	POOL_TEMP_DATA_P_READS	,
	POOL_XDA_P_READS	,
	POOL_TEMP_XDA_P_READS	,
	POOL_INDEX_P_READS	,
	POOL_TEMP_INDEX_P_READS	,
	POOL_DATA_WRITES	,
	POOL_XDA_WRITES		,
	POOL_INDEX_WRITES	,

	DIRECT_READ_TIME	,
	DIRECT_WRITE_TIME	,
	POOL_READ_TIME		,
	POOL_WRITE_TIME		,

	POOL_ASYNC_DATA_READS	,
	POOL_ASYNC_DATA_READ_REQS	,
	POOL_ASYNC_DATA_WRITES		,
	POOL_ASYNC_INDEX_READS		,
	POOL_ASYNC_INDEX_READ_REQS	,
	POOL_ASYNC_INDEX_WRITES		,
	POOL_ASYNC_XDA_READS		,
	POOL_ASYNC_XDA_READ_REQS	,
	POOL_ASYNC_XDA_WRITES	,

	VECTORED_IOS		,
	PAGES_FROM_VECTORED_IOS	,
	BLOCK_IOS		,
	PAGES_FROM_BLOCK_IOS	,
	UNREAD_PREFETCH_PAGES	,
	FILES_CLOSED		,

	TBSP_USED_PAGES		,
	TBSP_FREE_PAGES		,
	TBSP_USABLE_PAGES	,
	TBSP_TOTAL_PAGES	,
	TBSP_PENDING_FREE_PAGES	,
	TBSP_PAGE_TOP		,
	TBSP_MAX_PAGE_TOP	,
	RECLAIMABLE_SPACE_ENABLED,
	AUTO_STORAGE_HYBRID	,
	TBSP_PATHS_DROPPED	,
	POOL_ASYNC_READ_TIME	,
	POOL_ASYNC_WRITE_TIME	,
	STORAGE_GROUP_NAME	,
	STORAGE_GROUP_ID	,
	PREFETCH_WAIT_TIME	,
	PREFETCH_WAITS	,

	-- 05jun15 Adding on bits missed and pool/prefetch not related to purescale
	TABLESPACE_MIN_RECOVERY_TIME        ,
	TBSP_TRACKMOD_STATE  	  	        ,
	TBSP_DATATAG				,
	
	POOL_QUEUED_ASYNC_DATA_REQS		,
	POOL_QUEUED_ASYNC_INDEX_REQS		,
	POOL_QUEUED_ASYNC_TEMP_DATA_REQS	,
	POOL_QUEUED_ASYNC_TEMP_INDEX_REQS	,
	POOL_QUEUED_ASYNC_TEMP_XDA_REQS		,
	POOL_QUEUED_ASYNC_OTHER_REQS		,

	POOL_QUEUED_ASYNC_DATA_PAGES		,
	POOL_QUEUED_ASYNC_INDEX_PAGES		,
	POOL_QUEUED_ASYNC_XDA_REQS		,
	POOL_QUEUED_ASYNC_XDA_PAGES		,

	POOL_QUEUED_ASYNC_TEMP_DATA_PAGES	,
	POOL_QUEUED_ASYNC_TEMP_INDEX_PAGES	,
	POOL_QUEUED_ASYNC_TEMP_XDA_PAGES	,

	POOL_FAILED_ASYNC_DATA_REQS		,
	POOL_FAILED_ASYNC_INDEX_REQS		,
	POOL_FAILED_ASYNC_XDA_REQS		,

	POOL_FAILED_ASYNC_TEMP_DATA_REQS	,
	POOL_FAILED_ASYNC_TEMP_INDEX_REQS	,
	POOL_FAILED_ASYNC_TEMP_XDA_REQS		,
	POOL_FAILED_ASYNC_OTHER_REQS		,

	SKIPPED_PREFETCH_DATA_P_READS		,
	SKIPPED_PREFETCH_INDEX_P_READS		,
	SKIPPED_PREFETCH_XDA_P_READS		,

	SKIPPED_PREFETCH_TEMP_DATA_P_READS		,
	SKIPPED_PREFETCH_TEMP_INDEX_P_READS		,
	SKIPPED_PREFETCH_TEMP_XDA_P_READS		,

	SKIPPED_PREFETCH_UOW_DATA_P_READS		,
	SKIPPED_PREFETCH_UOW_INDEX_P_READS		,
	SKIPPED_PREFETCH_UOW_XDA_P_READS		,

	SKIPPED_PREFETCH_UOW_TEMP_DATA_P_READS		,
	SKIPPED_PREFETCH_UOW_TEMP_INDEX_P_READS		,
	SKIPPED_PREFETCH_UOW_TEMP_XDA_P_READS		

	
)
SELECT
	CURRENT TIMESTAMP,
	TBSP_NAME		,
	TBSP_ID 		,
	MEMBER 			,
	TBSP_TYPE 		,
	TBSP_CONTENT_TYPE 	,
	TBSP_STATE		,
	TBSP_PAGE_SIZE		,
	TBSP_EXTENT_SIZE	,
	TBSP_PREFETCH_SIZE	,
	TBSP_REBALANCER_MODE	,
	TBSP_USING_AUTO_STORAGE	,
	TBSP_AUTO_RESIZE_ENABLED,

	--counters
	DIRECT_READS		,
	DIRECT_READ_REQS	,
	DIRECT_WRITES		,
	DIRECT_WRITE_REQS	,
	POOL_DATA_L_READS	,
	POOL_TEMP_DATA_L_READS	,
	POOL_XDA_L_READS	,
	POOL_TEMP_XDA_L_READS	,
	POOL_INDEX_L_READS	,
	POOL_TEMP_INDEX_L_READS	,
	POOL_DATA_P_READS	,
	POOL_TEMP_DATA_P_READS	,
	POOL_XDA_P_READS	,
	POOL_TEMP_XDA_P_READS	,
	POOL_INDEX_P_READS	,
	POOL_TEMP_INDEX_P_READS	,
	POOL_DATA_WRITES	,
	POOL_XDA_WRITES		,
	POOL_INDEX_WRITES	,

	DIRECT_READ_TIME	,
	DIRECT_WRITE_TIME	,
	POOL_READ_TIME		,
	POOL_WRITE_TIME		,

	POOL_ASYNC_DATA_READS	,
	POOL_ASYNC_DATA_READ_REQS	,
	POOL_ASYNC_DATA_WRITES		,
	POOL_ASYNC_INDEX_READS		,
	POOL_ASYNC_INDEX_READ_REQS	,
	POOL_ASYNC_INDEX_WRITES		,
	POOL_ASYNC_XDA_READS		,
	POOL_ASYNC_XDA_READ_REQS	,
	POOL_ASYNC_XDA_WRITES	,

	VECTORED_IOS		,
	PAGES_FROM_VECTORED_IOS	,
	BLOCK_IOS		,
	PAGES_FROM_BLOCK_IOS	,
	UNREAD_PREFETCH_PAGES	,
	FILES_CLOSED		,

	TBSP_USED_PAGES		,
	TBSP_FREE_PAGES		,
	TBSP_USABLE_PAGES	,
	TBSP_TOTAL_PAGES	,
	TBSP_PENDING_FREE_PAGES	,
	TBSP_PAGE_TOP		,
	TBSP_MAX_PAGE_TOP	,
	RECLAIMABLE_SPACE_ENABLED,
	AUTO_STORAGE_HYBRID	,
	TBSP_PATHS_DROPPED	,
	POOL_ASYNC_READ_TIME	,
	POOL_ASYNC_WRITE_TIME	,
	STORAGE_GROUP_NAME	,
	STORAGE_GROUP_ID	,
	PREFETCH_WAIT_TIME	,
	PREFETCH_WAITS	,

	-- 05jun15 Adding on bits missed and pool/prefetch not related to purescale
	TABLESPACE_MIN_RECOVERY_TIME         ,   
	TBSP_TRACKMOD_STATE  	  	        ,
	TBSP_DATATAG				,
	
	POOL_QUEUED_ASYNC_DATA_REQS		,
	POOL_QUEUED_ASYNC_INDEX_REQS		,
	POOL_QUEUED_ASYNC_TEMP_DATA_REQS	,
	POOL_QUEUED_ASYNC_TEMP_INDEX_REQS	,
	POOL_QUEUED_ASYNC_TEMP_XDA_REQS		,
	POOL_QUEUED_ASYNC_OTHER_REQS		,

	POOL_QUEUED_ASYNC_DATA_PAGES		,
	POOL_QUEUED_ASYNC_INDEX_PAGES		,
	POOL_QUEUED_ASYNC_XDA_REQS		,
	POOL_QUEUED_ASYNC_XDA_PAGES				,

	POOL_QUEUED_ASYNC_TEMP_DATA_PAGES	,
	POOL_QUEUED_ASYNC_TEMP_INDEX_PAGES	,
	POOL_QUEUED_ASYNC_TEMP_XDA_PAGES	,

	POOL_FAILED_ASYNC_DATA_REQS		,
	POOL_FAILED_ASYNC_INDEX_REQS		,
	POOL_FAILED_ASYNC_XDA_REQS		,

	POOL_FAILED_ASYNC_TEMP_DATA_REQS	,
	POOL_FAILED_ASYNC_TEMP_INDEX_REQS	,
	POOL_FAILED_ASYNC_TEMP_XDA_REQS		,
	POOL_FAILED_ASYNC_OTHER_REQS		,

	SKIPPED_PREFETCH_DATA_P_READS		BIGINT,
	SKIPPED_PREFETCH_INDEX_P_READS		BIGINT,
	SKIPPED_PREFETCH_XDA_P_READS		BIGINT,

	SKIPPED_PREFETCH_TEMP_DATA_P_READS		BIGINT,
	SKIPPED_PREFETCH_TEMP_INDEX_P_READS		BIGINT,
	SKIPPED_PREFETCH_TEMP_XDA_P_READS		BIGINT,

	SKIPPED_PREFETCH_UOW_DATA_P_READS		BIGINT,
	SKIPPED_PREFETCH_UOW_INDEX_P_READS		BIGINT,
	SKIPPED_PREFETCH_UOW_XDA_P_READS		BIGINT,

	SKIPPED_PREFETCH_UOW_TEMP_DATA_P_READS		BIGINT,
	SKIPPED_PREFETCH_UOW_TEMP_INDEX_P_READS		BIGINT,
	SKIPPED_PREFETCH_UOW_TEMP_XDA_P_READS		BIGINT



FROM
	TABLE(MON_GET_TABLESPACE(NULL, -1)) -- CURRENT DB
;
--COMMIT;
--QUIT;

ECHO ******************************************;
ECHO TAKING DUBPERF_MONCONTAINER START SNAPSHOT;
ECHO ******************************************;
INSERT INTO  DBMON.DUBPERF_MONCONTAINER_START
(
	START_TIMESTAMP
	,TBSP_NAME 		
	,TBSP_ID 		
	,CONTAINER_NAME 		
	,CONTAINER_ID 		
	,MEMBER 			
	,CONTAINER_TYPE 		
	,STRIPE_SET 		
	,DIRECT_READS 		
	,DIRECT_WRITES 		
	,DIRECT_READ_TIME 	
	,DIRECT_WRITE_TIME 	
	,PAGES_READ 		
	,PAGES_WRITTEN 		
	,VECTORED_IOS 		
	,PAGES_FROM_VECTORED_IOS 
	,BLOCK_IOS 		
	,PAGES_FROM_BLOCK_IOS 	
	,POOL_READ_TIME 		
	,POOL_WRITE_TIME 	
	,TOTAL_PAGES 		
	,USABLE_PAGES 		
	,ACCESSIBLE 		
	,FS_ID 			
	,FS_TOTAL_SIZE 		
	,FS_USED_SIZE
)

SELECT
	CURRENT TIMESTAMP

	,TBSP_NAME 		
	,TBSP_ID 		
	,CONTAINER_NAME 		
	,CONTAINER_ID 		
	,MEMBER 			
	,CONTAINER_TYPE 		
	,STRIPE_SET 		
	,DIRECT_READS 		
	,DIRECT_WRITES 		
	,DIRECT_READ_TIME 	
	,DIRECT_WRITE_TIME 	
	,PAGES_READ 		
	,PAGES_WRITTEN 		
	,VECTORED_IOS 		
	,PAGES_FROM_VECTORED_IOS 
	,BLOCK_IOS 		
	,PAGES_FROM_BLOCK_IOS 	
	,POOL_READ_TIME 		
	,POOL_WRITE_TIME 	
	,TOTAL_PAGES 		
	,USABLE_PAGES 		
	,ACCESSIBLE 		
	,FS_ID 			
	,FS_TOTAL_SIZE 		
	,FS_USED_SIZE

FROM 
	TABLE(MON_GET_CONTAINER(NULL, -1)) -- CURRENT DB
;

ECHO ******************************************;
ECHO TAKING DUBPERF_MONINDEX START SNAPSHOT;
ECHO ******************************************;
INSERT INTO  DBMON.DUBPERF_MONINDEX_START
(
	SNAP_TIMESTAMP 	,
	TABSCHEMA 		,
	TABNAME 		,
	IID 			,
	MEMBER 			,
	DATA_PARTITION_ID 	,
	NLEAF 			,
	NLEVELS 		,
	INDEX_SCANS 		,
	INDEX_ONLY_SCANS 	,
	KEY_UPDATES 		,
	INCLUDE_COL_UPDATES 	,
	PSEUDO_DELETES 		,
	DEL_KEYS_CLEANED 	,
	ROOT_NODE_SPLITS 	,
	INT_NODE_SPLITS		,
	BOUNDARY_LEAF_NODE_SPLITS,
	NONBOUNDARY_LEAF_NODE_SPLITS,
	PAGE_ALLOCATIONS 	,
	PSEUDO_EMPTY_PAGES 	,
	EMPTY_PAGES_REUSED 	,
	EMPTY_PAGES_DELETED 	,
	PAGES_MERGED 		
)

SELECT
	CURRENT TIMESTAMP 	,
	TABSCHEMA 		,
	TABNAME 		,
	IID 			,
	MEMBER 			,
	DATA_PARTITION_ID 	,
	NLEAF 			,
	NLEVELS 		,
	INDEX_SCANS 		,
	INDEX_ONLY_SCANS 	,
	KEY_UPDATES 		,
	INCLUDE_COL_UPDATES 	,
	PSEUDO_DELETES 		,
	DEL_KEYS_CLEANED 	,
	ROOT_NODE_SPLITS 	,
	INT_NODE_SPLITS		,
	BOUNDARY_LEAF_NODE_SPLITS,
	NONBOUNDARY_LEAF_NODE_SPLITS,
	PAGE_ALLOCATIONS 	,
	PSEUDO_EMPTY_PAGES 	,
	EMPTY_PAGES_REUSED 	,
	EMPTY_PAGES_DELETED 	,
	PAGES_MERGED 		


FROM 
	TABLE(MON_GET_INDEX(NULL, NULL, NULL))
;

ECHO ******************************************;
ECHO TAKING DUBPERF_MONTABLE START SNAPSHOT;
ECHO ******************************************;
INSERT INTO  DBMON.DUBPERF_MONTABLE_START
(
	START_TIMESTAMP 	,
	TABSCHEMA 		,
	TABNAME 		,
	MEMBER 			,
	TAB_TYPE 		,
	TAB_FILE_ID 		,
	DATA_PARTITION_ID 	,
	TBSP_ID 		,
	INDEX_TBSP_ID 		,
	LONG_TBSP_ID 		,
	TABLE_SCANS 		,
	ROWS_READ 		,
	ROWS_INSERTED 		,
	ROWS_UPDATED 		,
	ROWS_DELETED 		,
	OVERFLOW_ACCESSES 	,
	OVERFLOW_CREATES 	,
	PAGE_REORGS 		
)

SELECT
	CURRENT TIMESTAMP 	,
	TABSCHEMA 		,
	TABNAME 		,
	MEMBER 			,
	TAB_TYPE 		,
	TAB_FILE_ID 		,
	DATA_PARTITION_ID 	,
	TBSP_ID 		,
	INDEX_TBSP_ID 		,
	LONG_TBSP_ID 		,
	TABLE_SCANS 		,
	ROWS_READ 		,
	ROWS_INSERTED 		,
	ROWS_UPDATED 		,
	ROWS_DELETED 		,
	OVERFLOW_ACCESSES 	,
	OVERFLOW_CREATES 	,
	PAGE_REORGS 		

FROM 
	TABLE(MON_GET_TABLE(NULL, NULL, NULL))
;
COMMIT;
ECHO ******************************************;
ECHO END OF DUBPERF START SNAPSHOTS;
ECHO ******************************************;
