WITH
  STATS (EXECUTABLE_ID, AVG_EXEC_TIME) AS
     (SELECT EXECUTABLE_ID, CASE WHEN NUM_EXEC_WITH_METRICS > 0 THEN STMT_EXEC_TIME / NUM_EXEC_WITH_METRICS ELSE 0 END AS ASTMT_EXEC_MSECS
        FROM TABLE (MON_GET_PKG_CACHE_STMT(NULL, NULL, NULL, -1))
           WHERE NOT STMT_TEXT LIKE '%MON_GET_%' AND NOT STMT_TEXT LIKE '%SYSPROC%' 
		         AND NOT STMT_TEXT LIKE '%EXPLAIN_%' AND NOT STMT_TEXT LIKE '%TABSCHEMA%')
SELECT EXECUTABLE_ID
FROM STATS
ORDER BY AVG_EXEC_TIME DESC
FETCH FIRST 15 ROWS ONLY;
